import { test, expect } from '@playwright/test';
for(const locale of ['en','zh'] as const) test(`${locale} calendar viewing preserves facts and manual creation is explicit`,async({page})=>{
 const t=(en:string,zh:string)=>locale==='zh'?zh:en;
 await page.clock.setFixedTime(new Date('2028-02-15T12:00:00Z'));
 await page.addInitScript(locale=>localStorage.setItem('fitness.language',locale),locale);
 await page.goto('/plans');await page.getByRole('button',{name:t('View month / day timeline and adjust training time','查看月 / 日时间轴并调整训练时间'),exact:true}).click();
 const calendar=page.getByRole('region',{name:t('training calendar','训练月历'),exact:true});
 await expect(calendar.locator('[data-calendar-date="2028-02-29"]')).toBeVisible();
 await calendar.locator('[data-calendar-date="2028-02-29"]').click();
 await calendar.getByRole('button',{name:t('day','日视图'),exact:true}).click();
 await expect(calendar.locator('.calendar-hour')).toHaveCount(24);
 await calendar.getByRole('button',{name:t('next day','后一天'),exact:true}).click();
 await expect(calendar.getByRole('heading',{level:2})).toContainText('2028');
 await calendar.getByRole('button',{name:t('month','月视图'),exact:true}).click();
 await expect(calendar.locator('[data-calendar-date="2028-03-01"]')).toBeVisible();
 await expect(page.getByLabel(t('Day plan name','日计划名称'),{exact:true})).toHaveCount(0);
 await page.getByRole('tab',{name:t('Create plan','创建计划'),exact:true}).click();
 await expect(page.getByRole('button',{name:t('Create manually','开始手动创建'),exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:t('Open AI plan wizard','进入 AI 计划向导'),exact:true})).toBeVisible();
 expect(await page.evaluate(async()=>{const {database}=await import(String('/src/persistence/db.ts'));return [await database.plans.count(),await database.sessions.count(),await database.sets.count()];})).toEqual([0,0,0]);
});
