import {test,expect} from '@playwright/test';
import {completedPlanningProfile} from './planning-profile-fixture';
test('reminder preferences persist across reload and theme changes without model requests',async({page})=>{
 let writes=0;await page.route('**/api/v1/**',r=>{if(r.request().method()!=='GET')writes++;return r.fulfill({status:503,json:{error:'CONTROL_UNAVAILABLE'}});});
 await completedPlanningProfile(page);await page.goto('/settings?tab=appearance');
 await page.getByRole('combobox',{name:'Daily maximum'}).selectOption('0');await page.getByLabel('Quiet hours start').fill('21:30');await page.getByLabel('Quiet hours end').fill('09:00');await page.getByRole('combobox',{name:'Coach dock side'}).selectOption('left');await page.getByRole('button',{name:'Save reminder preferences'}).click();await expect(page.getByText('Reminder preferences saved',{exact:true})).toBeVisible();await expect(page.locator('.coach-root')).toHaveAttribute('data-side','left');
 await page.reload();await expect(page.getByRole('combobox',{name:'Daily maximum'})).toHaveValue('0');await expect(page.getByLabel('Quiet hours start')).toHaveValue('21:30');await expect(page.getByLabel('Quiet hours end')).toHaveValue('09:00');await expect(page.getByRole('combobox',{name:'Coach dock side'})).toHaveValue('left');await page.getByLabel('Switch layout').selectOption('orbit');await expect(page.getByRole('combobox',{name:'Daily maximum'})).toHaveValue('0');expect(writes).toBe(0);
});
test('actual avatar component four states across all themes',async({page})=>{
 await page.goto('/settings');await page.setViewportSize({width:1000,height:600});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(async()=>{const p='/tests/e2e/helpers/coach-gallery.tsx';(await import(/* @vite-ignore */p)).renderGallery();});await expect(page.locator('#coach-gallery svg')).toHaveCount(12);await page.locator('#coach-gallery').screenshot({path:`outputs/v62-coach/avatar-states-${test.info().project.name}.png`});
});

test('short mobile viewport keeps the reply and send action reachable without losing input',async({page})=>{
 await page.route('**/api/v1/**',r=>r.fulfill({json:{expiresAt:Date.now()+86400000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},pending:0,aiEnabled:true}}));await completedPlanningProfile(page);await page.goto('/ai');await page.getByRole('textbox',{name:'Training goal and constraints',exact:true}).fill('Build a steady routine');await page.setViewportSize({width:390,height:450});await page.getByLabel('Reply to your coach').fill('Keep this reply while the viewport changes');await expect(page.getByRole('button',{name:'Agree to send and understand goal',exact:true})).toBeInViewport();await page.setViewportSize({width:390,height:844});await expect(page.getByLabel('Reply to your coach')).toHaveValue('Keep this reply while the viewport changes');
});

test('new route date selection requires explicit adoption in the retained conversation',async({page})=>{
 await page.route('**/api/v1/**',r=>r.fulfill({json:{expiresAt:Date.now()+86400000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},pending:0,aiEnabled:true}}));await completedPlanningProfile(page);await page.goto('/ai');await page.getByRole('textbox',{name:'Training goal and constraints',exact:true}).fill('Keep this current goal');await page.getByRole('button',{name:'Close coach conversation'}).click();await page.evaluate(()=>{history.pushState({usr:{selectedDates:['2026-10-15']},key:'selected-from-plans',idx:(history.state?.idx??0)+1},'','/ai');window.dispatchEvent(new PopStateEvent('popstate'));});await page.getByRole('button',{name:'Open coach conversation'}).click();await expect(page.getByRole('button',{name:'Use these dates'})).toBeVisible();await page.getByRole('button',{name:'Use these dates'}).click();await expect(page.getByRole('textbox',{name:'Training goal and constraints',exact:true})).toHaveValue('Keep this current goal');await expect(page.getByRole('button',{name:'Use these dates'})).toHaveCount(0);
});
