import {test,expect} from '@playwright/test';
import {completedPlanningProfile} from './planning-profile-fixture';
import {validateGuidedProviderOutput} from '../../src/backend/guided-provider';
test('modify previews and applies a real independent day; pause and cancellation require confirmation',async({page})=>{
 const sent:any[]=[];
 await page.route('**/api/v1/**',async route=>{
 if(route.request().method()==='GET')return route.fulfill({json:{expiresAt:Date.now()+86400000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},pending:0,aiEnabled:true}});
 const b=route.request().postDataJSON();sent.push(b);if(b.dialogue.coachTask==='manage')return route.fulfill({json:{requestId:b.requestId,accounting:'settled',result:validateGuidedProviderOutput(b.dialogue,{kind:'management_proposal',message:'Pause is optional.',impact:'History is retained; nothing has changed yet.',supportedOperations:['paused','active','terminated']}),context:{restoreGeneration:b.restoreGeneration,inputDigest:b.sendConfirmation}}});const exercise=b.dialogue.scope.conditions.existingPlan[0].exercises[0];const raw={kind:'change_proposal',targetPlanRef:b.dialogue.targetPlanRef,name:'Revised training',explanation:'Controlled fixture',days:[{date:b.dialogue.dates[0],exercises:[{...exercise,targetSets:[{metricType:'reps',reps:12}],setTimings:[{durationSeconds:45,restSeconds:45}]}]}]};return route.fulfill({json:{requestId:b.requestId,accounting:'settled',result:validateGuidedProviderOutput(b.dialogue,raw),context:{restoreGeneration:b.restoreGeneration,inputDigest:b.sendConfirmation}}});
 });
 await completedPlanningProfile(page);const id=await page.evaluate(async()=>{const d='/src/application/day-plans.ts',r='/src/persistence/repository.ts',e='/src/catalog/exercises.ts';const{dayPlanService}=await import(/* @vite-ignore */d),{repository}=await import(/* @vite-ignore */r),{exercises}=await import(/* @vite-ignore */e);const p=await repository.db.profiles.toCollection().first(),exercise=exercises.find((x:any)=>x.metricType==='reps'&&x.equipment==='none');return(await dayPlanService.saveDayPlan({name:'Original training',date:'2027-01-01',timeZone:p.timeZone,startTime:'12:00',durationMinutes:30,exercises:[{exerciseId:exercise.id,order:0,targetSets:[{metricType:'reps',reps:8}]}]})).plan.id;});
 await page.goto('/ai');await page.getByRole('button',{name:'Modify plan',exact:true}).click();await page.getByRole('combobox',{name:'Select plan',exact:true}).selectOption(id);await page.getByLabel('Your request / reason').fill('Increase the repetitions slightly');expect(sent).toHaveLength(0);
 await page.getByRole('checkbox',{name:/Send this plan and request/}).check();await page.getByRole('button',{name:'Generate proposed changes'}).click();await expect(page.getByRole('heading',{name:'Before → after (not saved)'})).toBeVisible();expect(sent).toHaveLength(1);expect(sent[0].dialogue.purpose).toBe('refine');expect(sent[0].dialogue.targetPlanRef.planId).toBe(id);expect(sent[0].dialogue.scope).not.toHaveProperty('history');expect(sent[0].dialogue.scope).not.toHaveProperty('body');
 await page.getByRole('button',{name:'Close coach conversation'}).click();await page.getByRole('button',{name:'Open AI coach',exact:true}).click();await expect(page.getByRole('heading',{name:'Before → after (not saved)'})).toBeVisible();
 await page.getByRole('checkbox',{name:/Replace this unstarted/}).check();await page.getByRole('button',{name:'Confirm changes',exact:true}).click();await expect(page.getByText('Plan changes saved.',{exact:true})).toBeVisible();expect(sent).toHaveLength(1);
 await page.getByRole('button',{name:'Pause / cancel',exact:true}).click();
 await page.getByRole('button',{name:'Agree to send and explain impact'}).click();await expect(page.getByText('Pause is optional.',{exact:false})).toBeVisible();expect(sent).toHaveLength(2);expect(sent[1].dialogue.scope).not.toHaveProperty('body');expect(sent[1].dialogue.scope).not.toHaveProperty('history');
 expect(await page.evaluate(async id=>{const p='/src/persistence/repository.ts';const{repository}=await import(p);return(await repository.db.plans.get(id)).status;},id)).toBe('active');await expect(page.getByRole('button',{name:'Confirm status change'})).toBeDisabled();await page.getByRole('checkbox',{name:'I reviewed the selected plan and consequences'}).check();await page.getByRole('button',{name:'Confirm status change'}).click();await expect(page.getByText('Plan status updated.',{exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('terminated');await expect(page.getByRole('button',{name:'Confirm status change'})).toBeDisabled();await page.getByRole('checkbox',{name:'I reviewed the selected plan and consequences'}).check();await page.getByRole('button',{name:'Confirm status change'}).click();expect(sent).toHaveLength(2);
 await expect.poll(()=>page.evaluate(async id=>{const p='/src/persistence/repository.ts';const{repository}=await import(/* @vite-ignore */p);return(await repository.db.plans.get(id)).status;},id)).toBe('archived');
});
test('AI optional suggestions do not block approval; essential refusal still blocks dates',async({page})=>{
 let calls=0;await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET')return route.fulfill({json:{expiresAt:Date.now()+86400000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:0,generate:4},pending:0,aiEnabled:true}});const b=route.request().postDataJSON();calls++;const raw=calls===1?{kind:'understand',summary:'Train four times with dumbbells.',uncertainties:['Would you like to rank your goals?'],draft:'Two strength sessions and two light conditioning sessions. Choose the dates next.'}:{kind:'refused',reason:'clarification_needed',message:'Please clarify an essential restriction.'};return route.fulfill({json:{requestId:b.requestId,accounting:'settled',result:validateGuidedProviderOutput(b.dialogue,raw),context:{restoreGeneration:b.restoreGeneration,inputDigest:b.sendConfirmation}}});});
 await completedPlanningProfile(page);await page.goto('/ai');await page.getByLabel('Training goal and constraints',{exact:true}).fill('Train four times with dumbbells');await page.getByRole('button',{name:'Agree to send and understand goal',exact:true}).click();await expect(page.getByText('Unscheduled draft · not saved')).toBeVisible();await page.getByRole('checkbox',{name:'I confirm this understanding is correct'}).check();await expect(page.getByRole('button',{name:'Choose dates →'})).toBeEnabled();
 await page.getByLabel('Reply to your coach').fill('A restriction needs clarification');await page.getByRole('button',{name:'Agree to send and understand goal',exact:true}).click();await expect(page.getByRole('button',{name:'Choose dates →'})).toBeDisabled();await expect(page.getByRole('checkbox',{name:'I confirm this understanding is correct'})).toHaveCount(0);await expect.poll(()=>calls).toBe(2);await expect(page.getByText('Please clarify an essential restriction.',{exact:true})).toBeVisible();
});
