import {test,expect} from '@playwright/test';
import {completedPlanningProfile} from './planning-profile-fixture';
for(const action of ['View','In 4 hours','Dismiss','Outside interaction','Route change'])test(`real reminder UI ${action} changes only reminder state`,async({page})=>{
 let posts=0;await page.route('**/api/v1/**',r=>{if(r.request().method()!=='GET')posts++;return r.fulfill({status:503,json:{error:'CONTROL_UNAVAILABLE'}});});
 await page.clock.install({time:new Date('2026-10-10T04:00:00Z')});await completedPlanningProfile(page);await page.goto('/settings?tab=appearance');await page.bringToFront();
 const fixture=await page.evaluate(async()=>{const c='/src/application/coach-reminders.ts',r='/src/persistence/repository.ts',d='/src/application/day-plans.ts',t='/src/domain/coach-reminders.ts';const{coachReminderService:s}=await import(/* @vite-ignore */c),{repository}=await import(/* @vite-ignore */r),{dayPlanService}=await import(/* @vite-ignore */d),{zonedMinute}=await import(/* @vite-ignore */t);const prefs=(await s.preferences()).preferences;const p=await repository.db.profiles.toCollection().first(),slot=zonedMinute(Date.now(),p.timeZone);await s.preferences({...prefs,enabled:true,weekdays:[new Date(slot.day+'T12:00:00Z').getUTCDay()||7],time:slot.time,quietStart:'00:00',quietEnd:'00:00'});await dayPlanService.saveDayPlan({name:'Real reminder UI',date:slot.day,timeZone:p.timeZone,startTime:slot.time,durationMinutes:30,exercises:[{exerciseId:'d16325d9-fc00-4c41-88a1-000000000003',order:0,targetSets:[{metricType:'reps',reps:8}]}]});return{day:slot.day,revision:(await repository.readMetadata()).dataRevision};});
 await page.clock.fastForward(31000);const bubble=page.getByRole('complementary',{name:'Training reminder'});await expect(bubble).toBeVisible();if(action==='Outside interaction')await page.getByRole('heading',{name:'Settings',exact:true}).click();else if(action==='Route change')await page.evaluate(()=>{history.pushState(null,'','/progress');dispatchEvent(new PopStateEvent('popstate'));});else await bubble.getByRole('button',{name:action,exact:true}).click();await expect(bubble).toHaveCount(0);
 if(action==='View')await expect(page).toHaveURL(new RegExp('/plans\\?date='+fixture.day));
 const checked=await page.evaluate(async()=>{const r='/src/persistence/repository.ts';const{repository}=await import(/* @vite-ignore */r);return{revision:(await repository.readMetadata()).dataRevision,ledger:(await repository.db.coachDevice.toArray())[0]};});
 expect(checked.revision).toBe(fixture.revision);expect(checked.ledger.records[0].status).toBe(action==='View'?'opened':action==='In 4 hours'?'snoozed':'dismissed');expect(posts).toBe(0);
});
