import {test,expect,type Page} from '@playwright/test';
async function facts(page:Page){return page.evaluate(async()=>{const path='/src/persistence/db.ts';const{database}=await import(/* @vite-ignore */path);return{sessions:await database.sessions.toArray(),sets:await database.sets.toArray(),tasks:await database.scheduledWorkouts.toArray()};});}
for(const locale of ['en','zh'] as const)test(`${locale} local workout pause and offline resume preserve facts through layout changes`,async({page,context})=>{
 const t=(en:string,zh:string)=>locale==='zh'?zh:en;await page.addInitScript(locale=>localStorage.setItem('fitness.language',locale),locale);await page.goto('/workout');
 await page.evaluate(async()=>{const w='/src/application/workouts.ts',p='/src/application/profile.ts',e='/src/catalog/exercises.ts';const{workoutService}=await import(/* @vite-ignore */w);const{profileService}=await import(/* @vite-ignore */p);const{exercises}=await import(/* @vite-ignore */e);const profile=await profileService.initialize('en');const session=await workoutService.startWorkout({sessionId:crypto.randomUUID(),localDate:'2026-10-08',timeZone:profile.timeZone,exerciseIds:[exercises.find((item:any)=>item.metricType==='reps').id]});await workoutService.recordSet(session.id,{id:crypto.randomUUID(),exerciseInstanceId:session.exerciseSnapshots[0].exerciseInstanceId,order:0,metricType:'reps',reps:8,completed:true},session.revision);});
 await expect(page.getByRole('button',{name:t('pause workout','暂停训练'),exact:true})).toBeVisible();const before=await facts(page);expect(before.sessions).toHaveLength(1);expect(before.sets).toHaveLength(1);
 await context.setOffline(true);await page.getByRole('button',{name:t('pause workout','暂停训练'),exact:true}).click();await expect(page.getByRole('button',{name:t('resume workout','恢复训练'),exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:t('Record set','记录组'),exact:true}).last()).toBeDisabled();
 for(const layout of ['serene','orbit','atlas']){await page.getByRole('combobox',{name:t('Switch layout','切换版式'),exact:true}).selectOption(layout);await expect(page.getByRole('button',{name:t('resume workout','恢复训练'),exact:true})).toBeVisible();expect((await facts(page)).sets).toEqual(before.sets);}
 await page.getByRole('button',{name:t('resume workout','恢复训练'),exact:true}).click();await expect(page.getByRole('button',{name:t('pause workout','暂停训练'),exact:true})).toBeVisible();const after=await facts(page);expect(after.sets).toEqual(before.sets);expect(after.sessions[0].status).toBe('in_progress');expect(after.tasks).toEqual(before.tasks);await context.setOffline(false);
});
test('calendar keyboard viewing is read-only and manual creation is available without onboarding',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('fitness.language','en'));await page.goto('/plans');const calendar=page.getByRole('tabpanel',{name:'Calendar',exact:true});await expect(calendar).toBeVisible();const before=await facts(page);
 const date=calendar.locator('[data-plan-date]').nth(15);await date.focus();await page.keyboard.press('ArrowRight');await expect(date).not.toBeFocused();await page.keyboard.press('Enter');
 await calendar.getByRole('button',{name:'Next month',exact:true}).click();await calendar.getByRole('button',{name:'Previous month',exact:true}).click();expect(await facts(page)).toEqual(before);
 await page.getByRole('tab',{name:'Create plan',exact:true}).click();await expect(page.getByRole('button',{name:'Create manually',exact:true})).toBeEnabled();await expect(page.getByRole('link',{name:'Open AI plan wizard',exact:true})).toHaveAttribute('href','/ai');
 for(const width of [320,375,390,420,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 expect(await facts(page)).toEqual(before);
});
