import { expect, test, type Page } from '@playwright/test';

test.setTimeout(60_000);
async function readLocal(page: Page) {
  return page.evaluate(async () => {
    const path = '/src/persistence/db.ts';
    const { database } = await import(/* @vite-ignore */ path);
    return { guided: await database.guidedStates.get('guided'), sessions: await database.sessions.toArray(), sets: await database.sets.toArray() };
  });
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
}

test('welcome: sample values stay unrecorded; keyboard confirmation, refresh and reset preserve old facts', async ({ page }, testInfo) => {
  await page.addInitScript(() => localStorage.setItem('fitness.language', 'zh'));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '你的年龄是多少？' })).toBeVisible();
  expect((await readLocal(page)).guided?.onboarding?.answers.age).toBeUndefined();
  await noOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('welcome-zh-320.png'), fullPage: true, animations: 'disabled' });
  await page.reload();
  await expect(page.getByRole('heading', { name: '你的年龄是多少？' })).toBeVisible();
  expect((await readLocal(page)).guided?.onboarding?.answers.age).toBeUndefined();
  await expect(page.getByRole('button', { name: '确认并继续', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: /填写数值/ }).click();
  const wheel = page.locator('[role="spinbutton"]').first();
  await wheel.focus(); await wheel.press('ArrowUp');
  await expect(wheel).toHaveAttribute('aria-valuenow', '31');
  expect((await readLocal(page)).guided?.onboarding?.answers.age).toBeUndefined();
  await page.getByRole('dialog').getByRole('button', { name: '确认选择' }).click();
  await page.getByRole('button', { name: '确认并继续', exact: true }).click();
  await expect(page.getByRole('heading', { name: '你的生理性别是？' })).toBeVisible();
  await page.getByRole('button', { name: /不愿透露/ }).click();
  await page.getByRole('button', { name: '确认并继续', exact: true }).click();
  await expect(page.getByRole('heading', { name: '你的身高是多少？' })).toBeVisible();
  expect((await readLocal(page)).guided.onboarding.answers.age).toEqual({ status: 'answered', value: 31 });
  await page.reload();
  await expect(page.getByRole('heading', { name: '你的身高是多少？' })).toBeVisible();
  await page.getByRole('button', { name: '跳过', exact: true }).click();
  await expect(page.getByRole('heading', { name: '你现在的体重是多少？' })).toBeVisible();
  expect((await readLocal(page)).guided.onboarding.answers.heightCm).toEqual({ status: 'skipped' });
  await page.getByRole('button', { name: '返回', exact: true }).click();
  await expect(page.getByRole('heading', { name: '你的身高是多少？' })).toBeVisible();
  await page.evaluate(async () => {
    const workoutPath = '/src/application/workouts.ts'; const profilePath = '/src/application/profile.ts'; const catalogPath = '/src/catalog/exercises.ts';
    const { workoutService } = await import(/* @vite-ignore */ workoutPath);
    const { profileService } = await import(/* @vite-ignore */ profilePath);
    const { exercises } = await import(/* @vite-ignore */ catalogPath);
    const profile = await profileService.getProfile();
    const session = await workoutService.startWorkout({ sessionId: crypto.randomUUID(), localDate: '2026-10-01', timeZone: profile.timeZone, exerciseIds: [exercises.find((item: { metricType: string }) => item.metricType === 'reps').id] });
    const saved = await workoutService.recordSet(session.id, { id: crypto.randomUUID(), exerciseInstanceId: session.exerciseSnapshots[0].exerciseInstanceId, order: 0, metricType: 'reps', reps: 8, completed: true }, session.revision);
    await workoutService.completeWorkout(session.id, saved.revision);
  });
  await expect(page.getByRole('heading', { name: '你的身高是多少？' })).toBeVisible();
  const before = await readLocal(page);
  await page.getByRole('button', { name: '重新开始引导', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('button', { name: '保留进度' })).toBeFocused();
  await dialog.getByRole('button', { name: '确认重新开始' }).click();
  await expect(page.getByRole('heading', { name: '你的年龄是多少？' })).toBeVisible();
  const after = await readLocal(page);
  expect(after.guided.onboarding?.answers ?? {}).toEqual({});
  expect(after.sessions).toEqual(before.sessions); expect(after.sets).toEqual(before.sets);
  await page.locator('.language-control select').selectOption('en');
  await expect(page.getByRole('heading', { name: 'how old are you?' })).toBeVisible();
  await noOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('welcome-en-320.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'view your dashboard first' }).click();
  await page.getByRole('button', { name: 'menu', exact: true }).click();
  await page.getByRole('link', { name: 'Plans', exact: true }).click();
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /create plan|save plan|创建计划|保存计划/i })).toHaveCount(0);
});

for (const locale of ['zh', 'en'] as const) {
  test(`${locale}: explicit mock understanding, candidate adoption, immediate pause and offline workout resume`, async ({ page, context }, testInfo) => {
    const text = (zh: string, en: string) => locale === 'zh' ? zh : en;
    await page.addInitScript(language => localStorage.setItem('fitness.language', language), locale);
    await page.goto('/');
    await expect(page.locator('.guided-onboarding')).toBeVisible();
    await page.getByRole('button', { name: text('先查看记录面板', 'view your dashboard first') }).click();
    await page.getByRole('button', { name: text('聊一聊计划', 'discuss your plan') }).click();
    await expect(page.getByRole('status').filter({ hasText: text('本地合成演示', 'local synthetic demo') })).toBeVisible();
    const goal = text('建立规律训练，优先徒手', 'build a regular bodyweight routine');
    await page.getByLabel(text('目标、补充或调整想法', 'goal, clarification or changes'), { exact: true }).fill(goal);
    await page.getByRole('button', { name: text('预览理解目标的发送范围', 'preview scope for understanding'), exact: true }).click();
    const scope = page.locator('section').filter({ has: page.getByRole('heading', { name: text('本次发送范围', 'sending scope'), exact: true }) });
    await expect(scope.locator('pre')).toContainText(goal);
    await expect(scope.locator('pre')).not.toContainText('"history"');
    await expect(scope.locator('pre')).not.toContainText('"body"');
    expect((await readLocal(page)).guided?.programs ?? []).toHaveLength(0);
    await scope.getByRole('button', { name: text('确认发送', 'confirm sending'), exact: true }).click();
    await page.getByText(text('核对目标和具体日期', 'review the goal and exact dates'), { exact: true }).click();
    await expect(page.getByRole('textbox', { name: text('目标理解', 'goal interpretation'), exact: true })).toHaveValue(goal);
    const today = await page.evaluate(() => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; });
    await page.getByLabel(text('开始日期', 'start date'), { exact: true }).fill(today);
    await page.getByLabel(text('结束日期', 'end date'), { exact: true }).fill(today);
    await page.getByRole('button', { name: today, exact: true }).click();
    await page.getByRole('button', { name: text('确认理解', 'confirm interpretation'), exact: true }).click();
    await page.getByRole('button', { name: text('预览本次发送范围', 'preview sending scope'), exact: true }).click();
    await scope.getByRole('button', { name: text('确认发送', 'confirm sending'), exact: true }).click();
    await expect(page.getByRole('heading', { name: text('完整候选，尚未生效', 'complete candidate, not active yet') })).toBeVisible();
    expect((await readLocal(page)).guided.programs).toHaveLength(0);
    await noOverflow(page);
    await page.screenshot({ path: testInfo.outputPath(`candidate-${locale}-320.png`), fullPage: true });
    const retainedCandidate = (await readLocal(page)).guided.candidates;
    await page.getByLabel(text('合成主题判定注入', 'synthetic topic decision injection')).selectOption('unrelated');
    await page.getByRole('textbox', { name: text('目标、补充或调整想法', 'goal, clarification or changes'), exact: true }).fill('write a programming tutorial');
    await expect(page.getByRole('button', { name: text('确认完整计划', 'confirm complete plan'), exact: true })).toBeDisabled();
    await page.getByRole('button', { name: text('预览理解目标的发送范围', 'preview scope for understanding'), exact: true }).click();
    await scope.getByRole('button', { name: text('确认发送', 'confirm sending'), exact: true }).click();
    await expect(page.getByRole('log', { name: text('对话记录', 'conversation') })).toContainText(text('不能处理无关娱乐', 'cannot handle unrelated entertainment'));
    expect((await readLocal(page)).guided.candidates).toEqual(retainedCandidate);
    expect((await readLocal(page)).guided.programs).toHaveLength(0);
    await expect(page.getByRole('textbox', { name: text('目标、补充或调整想法', 'goal, clarification or changes'), exact: true })).toHaveValue('write a programming tutorial');
    await page.getByRole('button', { name: text('按此候选重新核对', 'review this candidate again'), exact: true }).click();
    await page.getByRole('button', { name: text('确认理解', 'confirm interpretation'), exact: true }).click();
    await page.getByRole('button', { name: text('确认完整计划', 'confirm complete plan'), exact: true }).click();
    await expect.poll(async () => (await readLocal(page)).guided.programs.filter((item: { status: string }) => item.status === 'active').length).toBe(1);
    await page.getByRole('link', { name: text('返回记录面板', 'return to dashboard'), exact: true }).click();
    await expect(page.getByRole('heading', { name: text('时间进度', 'time progress'), exact: true })).toBeVisible();
    await expect(page.locator('.guided-dashboard').getByRole('heading', { name: text('训练完成进度', 'completed workouts'), exact: true })).toBeVisible();
    await expect(page.getByText(text('安全提醒：', 'safety: '), { exact: false })).toBeVisible();
    await noOverflow(page);
    await page.screenshot({ path: testInfo.outputPath(`dashboard-${locale}-320.png`), fullPage: true });
    const calendar = page.getByRole('region', { name: text('训练月历', 'training calendar'), exact: true });
    const beforeCalendar = await readLocal(page);
    await expect(calendar).toContainText(text('待训练', 'scheduled'));
    await expect(calendar.locator('.guided-calendar-exercise')).not.toHaveCount(0);
    await calendar.getByRole('button', { name: text('下个月', 'next month'), exact: true }).click();
    await calendar.getByRole('button', { name: text('上个月', 'previous month'), exact: true }).click();
    expect(await readLocal(page)).toEqual(beforeCalendar);
    await calendar.getByRole('button', { name: text('日视图', 'day'), exact: true }).click();
    await expect(calendar.locator('.calendar-timeline')).toBeVisible();
    await expect(calendar.locator('.calendar-now')).toBeVisible();
    await expect(calendar).toContainText(text('灵活安排 · 未设置具体时间', 'flexible · no scheduled time'));
    await calendar.getByRole('button', { name: text('后一天', 'next day'), exact: true }).click();
    await expect(calendar.locator('.calendar-now')).toHaveCount(0);
    await calendar.getByRole('button', { name: text('前一天', 'previous day'), exact: true }).click();
    await calendar.screenshot({ path: testInfo.outputPath(`calendar-day-${locale}.png`) });
    await calendar.getByRole('button', { name: text('月视图', 'month'), exact: true }).click();
    for (const width of [320,375,390,430,768,1024,1440]) {
      await page.setViewportSize({ width, height: 900 }); await noOverflow(page);
      const box = await calendar.locator('[data-calendar-date]').first().boundingBox();
      expect(box!.width).toBeGreaterThanOrEqual(44); expect(box!.height).toBeGreaterThanOrEqual(44);
    }
    const dateButton = calendar.locator(`[data-calendar-date="${today}"]`);
    await dateButton.focus(); await dateButton.press('ArrowRight');
    await expect(calendar.locator('[data-calendar-date]:focus')).not.toHaveAttribute('data-calendar-date',today);
    await calendar.getByRole('button', { name:text('选择多个日期','select multiple days'),exact:true }).click();
    await dateButton.click();
    await expect(calendar.getByRole('status')).toContainText(text('仅浏览，不覆盖或保存。','browse only; no overwrite or save.'));
    expect(await readLocal(page)).toEqual(beforeCalendar);
    await calendar.getByRole('button', { name:text('选择多个日期','select multiple days'),exact:true }).click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await noOverflow(page);
    await page.screenshot({ path: testInfo.outputPath(`dashboard-${locale}-desktop.png`), fullPage: true });
    await page.setViewportSize({ width: 320, height: 700 });
    await context.setOffline(true);
    await page.getByRole('button', { name: text('暂停计划', 'pause plan'), exact: true }).click();
    await expect(page).toHaveURL(/\/ai$/);
    expect((await readLocal(page)).guided.programs[0].status).toBe('paused');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('link', { name: text('返回记录面板', 'return to dashboard'), exact: true }).click();
    await page.getByRole('button', { name: text('恢复原计划', 'resume plan'), exact: true }).click();
    const resumeDialog = page.getByRole('dialog');
    await expect(resumeDialog.getByRole('button', { name: text('返回', 'back'), exact: true })).toBeFocused();
    await resumeDialog.getByRole('button', { name: text('确认', 'confirm'), exact: true }).click();
    await expect(resumeDialog).not.toBeVisible();
    expect((await readLocal(page)).guided.programs[0].status).toBe('active');
    await page.getByRole('button', { name: text('查看训练', 'view workout'), exact: true }).click();
    await page.getByRole('button', { name: text('开始计划训练', 'Start planned workout'), exact: true }).first().click();
    await page.getByLabel(text('次数', 'Reps'), { exact: true }).fill('8');
    await page.getByRole('button', { name: text('记录组', 'Record set'), exact: true }).click();
    await expect(page.getByRole('status').filter({ hasText: text('组已保存', 'Set saved') })).toBeVisible();
    await page.getByRole('button', { name: text('暂停训练', 'pause workout'), exact: true }).click();
    await expect(page.getByRole('button', { name: text('恢复训练', 'resume workout'), exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: text('记录组', 'Record set'), exact: true }).last()).toBeDisabled();
    await page.getByRole('button', { name: text('恢复训练', 'resume workout'), exact: true }).click();
    await expect(page.getByRole('button', { name: text('暂停训练', 'pause workout'), exact: true })).toBeVisible();
    const facts = await readLocal(page);
    expect(facts.sessions).toHaveLength(1); expect(facts.sessions[0].status).toBe('in_progress'); expect(facts.sets).toHaveLength(1);
    await context.setOffline(false);
  });
}
