import { completedPlanningProfile } from './planning-profile-fixture';
import {expect,test,type Page} from '@playwright/test';
import {validateGuidedProviderOutput} from '../../src/backend/guided-provider';
import {exercises} from '../../src/catalog/exercises';
const exercise=exercises.find(item=>item.metricType==='reps'&&item.equipment==='none')!;
const status={expiresAt:Date.now()+86400000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},pending:0,aiEnabled:true};
async function begin(page:Page){await page.addInitScript(()=>localStorage.setItem('fitness.language','en'));await completedPlanningProfile(page);await page.goto('/ai');await page.getByRole('textbox',{name:'Training goal and constraints',exact:true}).fill('Build a regular fitness routine');await page.getByRole('button',{name:'Agree to send and understand goal',exact:true}).click();}
async function dates(page:Page,count=1){await page.getByRole('checkbox',{name:'I confirm this understanding is correct',exact:true}).check();await page.getByRole('button',{name:'Choose dates →',exact:true}).click();for(let i=0;i<count;i++)await page.locator('[data-plan-date]').nth(15+i).click();}
async function preview(page:Page){await page.getByRole('button',{name:'Review sending →',exact:true}).click();await page.getByRole('checkbox',{name:/I confirm these fields and dates/}).check();}
function raw(body:any){return body.operation==='understand'?{kind:'understand',summary:'A ready goal',uncertainties:[]}:{kind:'program',name:'Four independent days',explanation:'Synthetic schedule',days:body.dialogue.dates.map((date:string)=>({date,exercises:[{exerciseId:exercise.id,order:0,targetSets:[{metricType:'reps',reps:8}],setTimings:[{durationSeconds:40,restSeconds:30}],notes:'Controlled tempo'}]}))};}
function response(body:any,accounting='settled'){return {requestId:body.requestId,result:validateGuidedProviderOutput(body.dialogue,raw(body)),accounting,context:{restoreGeneration:body.restoreGeneration,inputDigest:body.sendConfirmation}};}
for(const bounded of [false,true])test(`pending accounting gates generation; independent daily times save once; bounded=${bounded}`,async({page})=>{
 let pending=false;const sent:any[]=[];await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET')return route.fulfill({json:{...status,pending:pending?1:0,reconciliationRequired:pending&&!bounded}});const body=route.request().postDataJSON();sent.push(body);pending=true;return route.fulfill({json:response(body,'pending')});});
 await begin(page);await dates(page,4);const times=['12:00','14:00','09:00','20:00'];for(let i=0;i<4;i++)await page.getByLabel('Start time',{exact:true}).nth(i).fill(times[i]);await preview(page);
 if(!bounded){await expect(page.getByRole('button',{name:'Generate proposal →',exact:true})).toBeDisabled();pending=false;await page.getByRole('button',{name:'Refresh access',exact:true}).click();}
 expect(sent).toHaveLength(1);await page.getByRole('button',{name:'Generate proposal →',exact:true}).click();await expect(page.getByLabel('Plan name',{exact:true})).toHaveValue('Four independent days');
 expect(sent).toHaveLength(2);expect(sent[1].dialogue.schedule.map((slot:any)=>slot.startTime)).toEqual(times);
 const read=()=>page.evaluate(async()=>{const path='/src/persistence/db.ts';const{database}=await import(/* @vite-ignore */path);return{tasks:(await database.scheduledWorkouts.toArray()).sort((a:any,b:any)=>a.scheduledDate.localeCompare(b.scheduledDate)),sessions:await database.sessions.count(),sets:await database.sets.count(),state:await database.guidedStates.get('guided')};});
 expect((await read()).tasks).toHaveLength(0);await page.getByRole('checkbox',{name:/I reviewed each day/}).check();await page.getByRole('button',{name:'Confirm & save all daily plans'}).click();await expect(page.getByRole('button',{name:'Saved',exact:true})).toBeDisabled();
 const saved=await read();expect(saved.tasks.map((task:any)=>task.startTime)).toEqual(times);expect(saved.sessions).toBe(0);expect(saved.sets).toBe(0);expect(saved.state.programs).toHaveLength(0);expect(sent).toHaveLength(2);
 await page.reload();expect((await read()).tasks).toEqual(saved.tasks);expect(sent).toHaveLength(2);
});
test('failed confirmed generation retries only generation with identical identity and payload',async({page})=>{
 const sent:any[]=[];await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET')return route.fulfill({json:status});const body=route.request().postDataJSON();sent.push(body);return body.operation==='generate'?route.fulfill({status:503,json:{error:'CONTROL_UNAVAILABLE'}}):route.fulfill({json:response(body)});});
 await begin(page);await dates(page);await preview(page);await page.getByRole('button',{name:'Generate proposal →',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();expect(sent.map(item=>item.operation)).toEqual(['understand','generate']);await page.getByRole('button',{name:'Retry this generation request',exact:true}).click();await expect.poll(()=>sent.length).toBe(3);expect(sent[2]).toEqual(sent[1]);
});
test('uncertain understanding retry preserves request identity and excludes optional data',async({page})=>{
 const sent:any[]=[];await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET')return route.fulfill({json:status});sent.push(route.request().postDataJSON());return route.fulfill({status:503,json:{error:'CONTROL_UNAVAILABLE'}});});await begin(page);await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Agree to retry this understanding request',exact:true}).click();await expect.poll(()=>sent.length).toBe(2);expect(sent[1]).toEqual(sent[0]);expect(sent[0].dialogue.scope).not.toHaveProperty('body');expect(sent[0].dialogue.scope).not.toHaveProperty('history');
});
test('in-flight understanding locks edits; response does not automatically generate or save',async({page})=>{
 let release!:()=>void;const ready=new Promise<void>(resolve=>release=resolve);let posts=0;
 await page.route('**/api/v1/**',async route=>{if(route.request().method()==='GET')return route.fulfill({json:status});posts++;const body=route.request().postDataJSON();await ready;return route.fulfill({json:response(body)});});await begin(page);await expect.poll(()=>posts).toBe(1);await expect(page.getByRole('textbox',{name:'Training goal and constraints',exact:true})).toBeDisabled();release();await expect(page.getByText('A ready goal',{exact:true})).toBeVisible();expect(posts).toBe(1);await expect(page.getByRole('button',{name:'Choose dates →',exact:true})).toBeDisabled();
});

test('optional AI suggestions allow approval; revised goal requires fresh consent and excludes archived local notes',async({page})=>{
 const sent:any[]=[];await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET')return route.fulfill({json:status});const body=route.request().postDataJSON();sent.push(body);const result=validateGuidedProviderOutput(body.dialogue,{kind:'understand',summary:sent.length===1?'Build strength':'Build strength at home twice weekly',uncertainties:sent.length===1?['Where and how often can you train?']:[]});return route.fulfill({json:{requestId:body.requestId,result,accounting:'settled',context:{restoreGeneration:body.restoreGeneration,inputDigest:body.sendConfirmation}}});});
 await begin(page);await expect(page.getByText('Where and how often can you train?',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Choose dates →',exact:true})).toBeDisabled();await expect(page.getByRole('checkbox',{name:'I confirm this understanding is correct',exact:true})).toBeEnabled();
 await expect(page.getByRole('textbox',{name:'Training goal and constraints',exact:true})).toBeEnabled();await page.evaluate(async()=>{const p='/src/application/guided.ts';const{guidedService}=await import(/* @vite-ignore */p);await guidedService.appendMessage({id:crypto.randomUUID(),conversationId:crypto.randomUUID(),role:'user',content:'Private archived note not authorized',createdAt:new Date().toISOString()},(await guidedService.read()).revision);});
 await page.getByRole('textbox',{name:'Training goal and constraints',exact:true}).fill('Build strength at home twice weekly');await expect(page.getByRole('button',{name:'Agree to send and understand goal',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Agree to send and understand goal',exact:true}).click();await expect(page.locator('.v31-ai-understanding').getByText('Build strength at home twice weekly',{exact:true})).toBeVisible();await expect(page.getByRole('checkbox',{name:'I confirm this understanding is correct',exact:true})).toBeEnabled();expect(sent).toHaveLength(2);expect(JSON.stringify(sent)).not.toContain('Private archived note');expect(sent[1].dialogue.scope.conditions).not.toHaveProperty('priorDialogue');
});
