import {test,expect,type Page} from '@playwright/test';
async function prepare(page:Page,locale:string){
 await page.clock.setFixedTime(new Date('2026-10-06T12:00:00Z'));await page.goto('/');await page.getByRole('button',{name:'Start temporary workout',exact:true}).click();await page.getByLabel('Reps',{exact:true}).fill('8');await page.getByLabel('Load (kg)',{exact:true}).fill('0');await page.getByRole('button',{name:'Record set',exact:true}).click();await page.getByRole('button',{name:'Review completion',exact:true}).click();await page.getByRole('button',{name:'Confirm completion',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Workout completed');await page.goto('/progress');await page.getByLabel('Language').selectOption(locale);await expect.poll(()=>page.evaluate(async()=>{const path='/src/persistence/db.ts';const {database}=await import(/* @vite-ignore */ path) as typeof import('../../src/persistence/db');return (await database.profiles.toCollection().first())?.locale;})).toBe(locale);await page.getByRole('button',{name:locale==='zh'?'准备本地预览':'Prepare local preview',exact:true}).click();
}
const status=(pending=0)=>({expiresAt:Date.UTC(2027,0,1),period:'2026-10',used:{understand:0,generate:0,summary:0},limits:{understand:8,generate:4,summary:4},pending,reconciliationRequired:pending>0,summaryAvailable:true,aiEnabled:true});
const read=(page:Page)=>page.evaluate(async()=>{const path='/src/persistence/db.ts';const {database}=await import(/* @vite-ignore */ path) as typeof import('../../src/persistence/db');return database.transaction('r',database.tables,async()=>Promise.all(database.tables.map(async table=>({name:table.name,rows:await table.toArray()}))));});
for(const locale of ['en','zh'])test(`${locale} summary requires exact confirmation and preserves pending result without writes`,async({page})=>{
 const t=(en:string,zh:string)=>locale==='zh'?zh:en;let calls=0,submitted=0;
 await page.route('**/api/v1/**',async route=>{calls++;if(route.request().method()==='GET'){await route.fulfill({status:submitted?503:200,contentType:'application/json',body:JSON.stringify(submitted?{error:'CONTROL_UNAVAILABLE'}:status())});return;}submitted++;const input=route.request().postDataJSON();expect(Object.keys(input).sort()).toEqual(['contractVersion','locale','operation','requestId','restoreGeneration','sendConfirmation','stage']);expect(input.stage).not.toHaveProperty('manifest');expect(input.stage).not.toHaveProperty('report');expect(input.stage.completionLinks).toEqual([]);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({requestId:input.requestId,result:{summary:'Synthetic completed training summary',nextStageAdvice:['Keep a steady routine']},context:{restoreGeneration:input.restoreGeneration,inputDigest:input.sendConfirmation},accounting:'pending'})});});
 await prepare(page,locale);expect(calls).toBe(0);const before=await read(page),ai=page.getByRole('region',{name:t('AI stage summary','AI 阶段总结'),exact:true});await ai.getByRole('button',{name:t('Connect summary backend','连接总结后端'),exact:true}).click();expect(submitted).toBe(0);await ai.getByRole('button',{name:t('Preview summary sending','预览总结发送'),exact:true}).click();await expect(ai.getByRole('button',{name:t('Send confirmed summary','发送已确认总结'),exact:true})).toBeDisabled();await ai.getByLabel(t('I confirm this summary sending scope','我确认本次总结发送范围'),{exact:true}).check();await ai.getByRole('button',{name:t('Send confirmed summary','发送已确认总结'),exact:true}).click();
 const result=ai.getByRole('region',{name:t('Returned stage summary','已返回阶段总结'),exact:true});await expect(result).toContainText('Synthetic completed training summary');await expect(result).toContainText('Keep a steady routine');await expect(ai.getByRole('status')).toContainText(t('full reservation','完整预留'));await expect(ai.getByText(t('Summary qualification and allowance: unknown.','总结资格和额度：未知。'),{exact:true})).toBeVisible();await expect(ai.getByRole('button',{name:t('Preview summary sending','预览总结发送'),exact:true})).toBeDisabled();await ai.getByRole('button',{name:t('Refresh summary qualification','刷新总结资格'),exact:true}).click();await expect(result).toContainText('Synthetic completed training summary');expect(submitted).toBe(1);expect(await read(page)).toEqual(before);
 await page.getByLabel(t('Summary from date','总结起始日'),{exact:true}).fill('2026-10-05');await expect(ai.getByRole('region',{name:t('Summary sending scope','总结发送范围'),exact:true})).toHaveCount(0);await expect(result).toContainText('Synthetic completed training summary');
});
test('missing summary capability and allowance never enable sending',async({page})=>{
 await page.route('**/api/v1/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({expiresAt:Date.UTC(2027,0,1),period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},aiEnabled:true})}));await prepare(page,'en');const ai=page.getByRole('region',{name:'AI stage summary',exact:true});await ai.getByRole('button',{name:'Connect summary backend',exact:true}).click();await expect(ai.getByText(/Summary availability: unknown/)).toBeVisible();await expect(ai.getByRole('button',{name:'Preview summary sending',exact:true})).toBeDisabled();
});
test('cancelled summary ignores late output without retry or a success claim',async({page})=>{
 let submitted=0,release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/api/v1/**',async route=>{if(route.request().method()==='GET'){await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(status())});return;}if(route.request().url().endsWith('/cancel')){await route.fulfill({status:200,contentType:'application/json',body:'{}'});return;}submitted++;const input=route.request().postDataJSON();await gate;try{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({requestId:input.requestId,result:{summary:'Late ignored summary',nextStageAdvice:['Ignored']},context:{restoreGeneration:input.restoreGeneration,inputDigest:input.sendConfirmation},accounting:'pending'})});}catch{/* Browser aborts the isolated intercepted request. */}});
 await prepare(page,'en');const ai=page.getByRole('region',{name:'AI stage summary',exact:true});await ai.getByRole('button',{name:'Connect summary backend',exact:true}).click();await ai.getByRole('button',{name:'Preview summary sending',exact:true}).click();await ai.getByLabel('I confirm this summary sending scope',{exact:true}).check();await ai.getByRole('button',{name:'Send confirmed summary',exact:true}).click();await expect(ai.getByRole('button',{name:'Cancel summary request',exact:true})).toBeVisible();await ai.getByRole('button',{name:'Cancel summary request',exact:true}).click();release();await expect(ai.getByRole('alert')).toContainText('no refund is promised');await expect(ai.getByRole('region',{name:'Returned stage summary',exact:true})).toHaveCount(0);expect(submitted).toBe(1);await expect(ai.getByRole('button',{name:'Preview summary sending',exact:true})).toBeDisabled();
});
test('unrelated revision permits send but restore generation invalidates its confirmation',async({page})=>{
 let submitted=0,holdStatus=false,releaseStatus!:()=>void;const statusGate=new Promise<void>(resolve=>{releaseStatus=resolve;});await page.route('**/api/v1/**',async route=>{if(route.request().method()==='GET'){if(holdStatus)await statusGate;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(status())});return;}submitted++;const input=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({requestId:input.requestId,result:{summary:'First valid summary',nextStageAdvice:['Text only']},context:{restoreGeneration:input.restoreGeneration,inputDigest:input.sendConfirmation},accounting:'settled'})});});await prepare(page,'en');const ai=page.getByRole('region',{name:'AI stage summary',exact:true});await ai.getByRole('button',{name:'Connect summary backend',exact:true}).click();
 async function preview(){await ai.getByRole('button',{name:'Preview summary sending',exact:true}).click();await ai.getByLabel('I confirm this summary sending scope',{exact:true}).check();}
 await preview();await page.evaluate(async()=>{const path='/src/persistence/db.ts';const {database}=await import(/* @vite-ignore */ path) as typeof import('../../src/persistence/db');const metadata=await database.metadata.toCollection().first();await database.metadata.update(metadata!.localProfileId,{dataRevision:metadata!.dataRevision+1});});await ai.getByRole('button',{name:'Send confirmed summary',exact:true}).click();await expect(ai.getByRole('region',{name:'Returned stage summary',exact:true})).toContainText('First valid summary');holdStatus=true;await ai.getByRole('button',{name:'Refresh summary qualification',exact:true}).click();await expect(ai.getByText('Processing summary…',{exact:true})).toBeVisible();await expect(ai.getByRole('button',{name:'Cancel summary request',exact:true})).toHaveCount(0);releaseStatus();await expect(ai.getByRole('button',{name:'Preview summary sending',exact:true})).toBeEnabled();await preview();await page.evaluate(async()=>{const path='/src/persistence/db.ts';const {database}=await import(/* @vite-ignore */ path) as typeof import('../../src/persistence/db');const metadata=await database.metadata.toCollection().first();await database.metadata.update(metadata!.localProfileId,{restoreGeneration:(metadata!.restoreGeneration??0)+1});});await expect(page.getByRole('button',{name:'Send confirmed summary',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Summary sending scope',exact:true})).toHaveCount(0);expect(submitted).toBe(1);
});
