import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
const oz=JSON.parse(readFileSync('src/i18n/features/onboarding/zh.json','utf8')),oe=JSON.parse(readFileSync('src/i18n/features/onboarding/en.json','utf8'));
const tz=JSON.parse(readFileSync('src/i18n/features/training/zh.json','utf8')),te=JSON.parse(readFileSync('src/i18n/features/training/en.json','utf8'));
const root='outputs/v8-cleanup';
for(const theme of ['qingci','liubai','jingshe','zhuangse'])for(const locale of (theme==='qingci'?['zh','en']:['zh']))for(const width of [390,1440])test(`${theme} ${locale} ${width} final matrix`,async({page})=>{
 test.setTimeout(120000);const o=locale==='zh'?oz:oe,t=locale==='zh'?tz:te;const metrics:any[]=[];
 await page.addInitScript(({theme,locale})=>{localStorage.setItem('fitness-theme',theme);localStorage.setItem('fitness.language',locale);},{theme,locale});
 await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});
 async function capture(name:string){await page.evaluate(()=>document.fonts.ready);await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{})));});const metric=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('button,summary,select,input,textarea')].filter(e=>(e as HTMLElement).offsetWidth>0).map(e=>{const target=(e instanceof HTMLInputElement&&e.type==='checkbox'?e.closest('label'):e)!;const r=target.getBoundingClientRect();return {tag:e.tagName,text:e.textContent?.slice(0,40),width:r.width,height:r.height};}),animations:document.getAnimations().filter(a=>a.playState==='running').length}));metrics.push({page:name,...metric});for(const c of metric.controls){expect(c.width,`${name} ${c.text}`).toBeGreaterThanOrEqual(44);expect(c.height,`${name} ${c.text}`).toBeGreaterThanOrEqual(44);}expect(metric.scrollWidth).toBeLessThanOrEqual(width);await page.screenshot({path:`${root}/screenshots/${theme}-${locale}-${width}-${name}.png`,fullPage:true});}
 await page.goto('/');await expect(page.locator('.v8-onboarding')).toBeVisible();await capture('01-onboarding');
 for(const answer of ['保持力量 / More strength','每周 3 次，每次 30 分钟','在家，只有瑜伽垫']){await page.getByLabel(o.answer,{exact:true}).fill(answer);await page.getByRole('button',{name:o.next,exact:true}).click();}await page.getByLabel(o.adult).check();await page.getByRole('button',{name:o.generate,exact:true}).click();await expect(page.getByRole('heading',{name:o.draft,exact:true})).toBeVisible();await capture('02-draft');await page.getByRole('button',{name:o.accept,exact:true}).click();await expect(page.getByRole('heading',{name:t.next,exact:true})).toBeVisible();await capture('03-next');
 await page.goto('/plans');await page.locator('.plan-items button').first().click();await expect(page.getByRole('dialog')).toBeVisible();await capture('04-capsule');await page.keyboard.press('Escape');await capture('08-plan');
 await page.goto('/');await page.getByRole('button',{name:t.start,exact:true}).first().click();await page.getByRole('button',{name:t.completeSet,exact:true}).click();await capture('05-training');
 if(width===390){await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${root}/screenshots/${theme}-${locale}-320-training.png`,fullPage:true});await page.setViewportSize({width,height:900});}
 await page.getByRole('button',{name:t.pause,exact:true}).click();await page.getByRole('button',{name:t.end,exact:true}).click();await capture('06-finish');await page.getByRole('button',{name:t.save,exact:true}).click();
 await page.goto('/activity');await capture('07-activity');
 await page.evaluate(async()=>{const p='/src/persistence/db.ts',db=(await import(/* @vite-ignore */ p)).database;const v=(await db.v8PlanVersions.toArray())[0];const dp='/src/application/v8-activity.ts',date=(await import(/* @vite-ignore */ dp)).activityDate('Asia/Shanghai');const item=v.templates[0].items[0];await db.v8Workouts.bulkAdd([0,1].map(i=>({id:crypto.randomUUID(),planVersionId:v.id,templateId:v.templates[0].id,startedAt:`${date}T0${i+2}:00:00Z`,endedAt:`${date}T0${i+2}:10:00Z`,localDate:date,timeZone:'Asia/Shanghai',status:'partial',plannedSetCount:8,sets:[{exerciseId:item.exerciseId,itemIndex:0,setIndex:0,reps:8,completedAt:`${date}T0${i+2}:01:00Z`}],feedback:{reasons:['time']}})));});
 await page.goto('/review');await expect(page.getByRole('button',{name:locale==='zh'?'就这样调整':'Use this adjustment',exact:true})).toBeVisible();await capture('09-week');await page.getByRole('button',{name:locale==='zh'?'本月回顾':'This month',exact:true}).click();await capture('10-month');
 await page.goto('/settings/appearance');await capture('11-appearance');
 await page.route('**/api/v1/plans/generate',async route=>{const x=route.request().postDataJSON(),r=x.coach;await route.fulfill({json:{requestId:x.requestId,context:{restoreGeneration:r.restoreGeneration,inputDigest:x.sendConfirmation},accounting:'settled',result:{requestId:x.requestId,restoreGeneration:r.restoreGeneration,mutationAllowed:false,type:'today_adjustment',target:r.target,template:{...r.template,items:r.template.items.map((i:any)=>({...i,sets:1}))},summary:locale==='zh'?'本次每个动作一组':'One set per exercise today'}}});});
 await page.goto('/');await page.getByRole('button',{name:t.askCoach,exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('textbox').fill(locale==='zh'?'今天少一组':'One fewer set today');await dialog.getByRole('button',{name:locale==='zh'?'发送':'Send',exact:true}).click();await expect(page.getByText(locale==='zh'?'本次每个动作一组':'One set per exercise today',{exact:true})).toBeVisible();await capture('12-coach');
 if(width===390){await page.keyboard.press('Escape');for(const [path,name]of [['/','next'],['/review','review']]){await page.goto(path);await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${root}/screenshots/${theme}-${locale}-320-${name}.png`,fullPage:true});}}
 mkdirSync(`${root}/metrics`,{recursive:true});writeFileSync(`${root}/metrics/${theme}-${locale}-${width}.json`,JSON.stringify(metrics,null,2));
});
