import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {liveQuery} from 'dexie';
import {repository} from '../../persistence/repository';
import {guidedService} from '../../application/guided';
import {coachPlanService} from '../../application/coach-plans';
import {guidedInputSnapshot,confirmGuidedSending} from '../../ai/guided-dialogue';
import {sendGuidedDialogue} from '../../ai/guided-transport';
import type {GuidedDialogueRequest} from '../../domain/guided-ai-contracts';
import type {Plan,PlanVersion,ScheduledWorkout} from '../../domain/models';
import type {ProgramCandidate} from '../../domain/guided-contracts';
import {CandidateEditor} from './guided/CandidateEditor';
import {localAgeAccess} from '../../domain/onboarding-v4';
import type {CoachVisualState} from './CoachAvatar';
type Source={plan:Plan;version:PlanVersion|undefined;tasks:ScheduledWorkout[]};
export function CoachPlanActions({mode,conversationId,onState,onBusy}:{mode:'modify'|'lifecycle';conversationId:string;onState?:(state:CoachVisualState)=>void;onBusy?:(busy:boolean)=>void}){
 const {i18n}=useTranslation(),zh=i18n.resolvedLanguage==='zh';const[rows,setRows]=useState<Source[]>([]),[id,setId]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[consent,setConsent]=useState(false),[confirm,setConfirm]=useState(false),[action,setAction]=useState<'paused'|'active'|'terminated'>('paused');const[candidate,setCandidate]=useState<ProgramCandidate>();
 const source=useRef<{value:Source;snapshot:string;generation:number;dependencies:Awaited<ReturnType<typeof guidedService.captureDependencies>>}|undefined>(undefined);const lifecycleReview=useRef<{generation:number;context:string;snapshot:string}|undefined>(undefined);const pending=useRef<GuidedDialogueRequest|undefined>(undefined);const abort=useRef<AbortController|undefined>(undefined);const lock=useRef(false);
 useEffect(()=>{const sub=liveQuery(async()=>{const plans=await repository.db.plans.toArray();return Promise.all(plans.filter(p=>!p.deletedAt&&p.status==='active').map(async plan=>({plan,version:await repository.db.planVersions.get(plan.currentVersionId),tasks:await repository.db.scheduledWorkouts.where('planVersionId').equals(plan.currentVersionId).toArray()})));}).subscribe({next:setRows,error:e=>setError(String(e))});return()=>{sub.unsubscribe();abort.current?.abort();};},[]);
 useEffect(()=>{setConfirm(false);setConsent(false);},[mode]);
 useEffect(()=>{onBusy?.(busy);return()=>onBusy?.(false);},[busy,onBusy]);
 const [reviewPending,setReviewPending]=useState(false);const reviewSequence=useRef(0);const [affected,setAffected]=useState<string[]>([]);
 useEffect(()=>{reviewSequence.current++;lifecycleReview.current=undefined;setConfirm(false);setReviewPending(false);void guidedService.read().then(state=>{const phase=state.programs.find(p=>p.planIds.includes(id)&&p.status!=='terminated');setAffected(rows.filter(r=>phase?phase.planIds.includes(r.plan.id):r.plan.id===id).map(r=>r.plan.name+' · '+r.tasks.map(t=>t.scheduledDate).join(', ')));});},[id,mode,action,rows]);
 const selected=rows.find(r=>r.plan.id===id);const reset=()=>{setCandidate(undefined);setConsent(false);setConfirm(false);pending.current=undefined;source.current=undefined;setNotice('');};
 const run=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(String(e));onState?.('idle');}finally{lock.current=false;setBusy(false);}};
 async function generate(){
   if(!selected||!consent||!note.trim())return;
   const state=await guidedService.read();if(localAgeAccess(state.onboarding?.answers??{})==='minor'||state.onboarding?.version===4&&(!state.onboarding.completed||localAgeAccess(state.onboarding.answers)!=='adult'))throw Error(zh?'需完成成人资料确认；手动训练仍可使用。':'Complete adult onboarding; manual training remains available.');
   const generation=(await repository.readMetadata()).restoreGeneration??0;
   if(selected.plan.model!=='date-day'||selected.tasks.length!==1||state.programs.some(p=>p.planIds.includes(id)))throw Error(zh?'此入口修改独立日计划；阶段计划和旧周课表请使用计划面板对应编辑器。':'This edits independent day plans. Use the plan workspace for managed phases or legacy week plans.');
   const task=selected.tasks[0];if(task.completedSessionId||task.hiddenAt||task.status!=='pending')throw Error('TRAINING_READ_ONLY');
   if(!task.startTime||!task.durationMinutes)throw Error(zh?'请先在计划面板确认本日开始时间与时长。':'Confirm this day’s start time and duration in Plans first.');
   if(!pending.current){
     const input={version:'guided-dialogue-v1' as const,conversationId,restoreGeneration:generation,purpose:'refine' as const,locale:zh?'zh' as const:'en' as const,scope:{goal:note.trim(),conditions:{existingPlan:selected.version!.days,planName:selected.plan.name}},startDate:task.scheduledDate,endDate:task.scheduledDate,dates:[task.scheduledDate],timeZone:selected.plan.scheduleTimeZone,schedule:[{date:task.scheduledDate,startTime:task.startTime,durationMinutes:task.durationMinutes}],confirmedSummary:note.trim(),refinement:note.trim(),candidateId:crypto.randomUUID(),...(state.onboarding?.version===4?{onboardingVersion:4 as const,adultConfirmed:true}:{})};
     pending.current={...input,requestId:crypto.randomUUID(),inputSnapshot:guidedInputSnapshot(input)};source.current={value:selected,snapshot:JSON.stringify(selected),generation,dependencies:await guidedService.captureDependencies()};
   }
   if(source.current?.snapshot!==JSON.stringify(selected)||source.current.generation!==generation)throw Error('STALE_INPUT');
   abort.current=new AbortController();onState?.('thinking');const result=await sendGuidedDialogue(pending.current,confirmGuidedSending(pending.current),abort.current.signal);
   if(abort.current.signal.aborted||(await repository.readMetadata()).restoreGeneration!==undefined&&((await repository.readMetadata()).restoreGeneration??0)!==generation)throw Error('STALE_INPUT');
   if(!('candidate' in result.response)){setNotice('message' in result.response?result.response.message:zh?'请补充说明后再试。':'Please clarify your request.');pending.current=undefined;onState?.('replying');return;}
   setCandidate({...result.response.candidate,...source.current!.dependencies});setConfirm(false);pending.current=undefined;onState?.('replying');
 }
 return <section><h2>{mode==='modify'?(zh?'调整训练计划':'Modify a plan'):(zh?'暂停／取消计划':'Pause / cancel a plan')}</h2><p>{zh?'选择已有计划并核对影响；不会自动改写或删除训练历史。':'Select an existing plan and review its impact. Completed training history is preserved.'}</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <fieldset disabled={busy}><label>{zh?'选择计划':'Select plan'}<select aria-label={zh?'选择计划':'Select plan'} value={id} onChange={e=>{setId(e.target.value);reset();}}><option value="">—</option>{rows.map(row=><option key={row.plan.id} value={row.plan.id}>{row.plan.name} · {row.tasks.map(t=>t.scheduledDate).join(', ')}</option>)}</select></label><label>{zh?'你的调整意图／原因':'Your request / reason'}<textarea value={note} onChange={e=>{setNote(e.target.value);reset();}}/></label></fieldset>
 {selected&&mode==='modify'&&<><details><summary>{zh?'本次发送的计划内容':'Plan information to send'}</summary><pre>{JSON.stringify({name:selected.plan.name,days:selected.version?.days,dates:selected.tasks.map(t=>({date:t.scheduledDate,startTime:t.startTime,durationMinutes:t.durationMinutes})),request:note},null,2)}</pre></details><label><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>{zh?'同意发送上述计划与调整意图给 AI；可能产生模型费用。身体资料与训练历史不发送。':'Send this plan and request to AI; model costs may apply. Body data and training history are excluded.'}</label><button disabled={!consent||busy||!note.trim()} onClick={()=>void run(generate)}>{pending.current?(zh?'重试原请求':'Retry original request'):(zh?'生成修改候选':'Generate proposed changes')}</button>{busy&&<button onClick={()=>abort.current?.abort()}>{zh?'停止等待（不代表免费）':'Stop waiting (costs may apply)'}</button>}
 {candidate&&<><h3>{zh?'修改前 → 修改后（尚未保存）':'Before → after (not saved)'}</h3><details><summary>{zh?'修改前内容':'Before'}</summary><pre>{JSON.stringify(source.current?.value.version?.days,null,2)}</pre></details><CandidateEditor candidate={candidate} locale={zh?'zh':'en'} disabled={busy} onChange={v=>{setCandidate(v);setConfirm(false);}}/><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>{zh?'确认替换这个未开始日计划的内容，保留训练历史。':'Replace this unstarted day plan; preserve training history.'}</label><button disabled={busy||!confirm} onClick={()=>void run(async()=>{const s=source.current!;await coachPlanService.apply(s.value.plan.id,s.value.plan.revision,s.generation,candidate,s.snapshot);setCandidate(undefined);setNotice(zh?'计划修改已保存。':'Plan changes saved.');onState?.('success');})}>{zh?'确认应用修改':'Confirm changes'}</button></>}
 </>}
 {selected&&mode==='lifecycle'&&<><ul aria-label={zh?'受影响计划':'Affected plans'}>{affected.map(name=><li key={name}>{name}</li>)}</ul><label>{zh?'操作':'Action'}<select aria-label={zh?'操作':'Action'} value={action} onChange={e=>{setAction(e.target.value as typeof action);setConfirm(false);}}><option value="paused">{zh?'暂停':'Pause'}</option><option value="active">{zh?'恢复':'Resume'}</option><option value="terminated">{zh?'取消后续安排':'Cancel future training'}</option></select></label><p>{zh?'暂停保留安排；取消终止关联阶段的后续训练，不可直接恢复。已完成记录保留；进行中的训练不会被静默结束。':'Pause retains the schedule. Cancellation terminates future training in the linked phase and cannot be directly resumed. Completed records remain; ongoing training is not silently ended.'}</p><label><input type="checkbox" checked={confirm} onChange={e=>{const checked=e.target.checked,sequence=++reviewSequence.current;setConfirm(checked);lifecycleReview.current=undefined;setReviewPending(checked);if(checked)void Promise.all([repository.readMetadata(),guidedService.capturePlanContext()]).then(([m,context])=>{if(sequence!==reviewSequence.current)return;lifecycleReview.current={generation:m.restoreGeneration??0,context,snapshot:JSON.stringify(selected)};setReviewPending(false);}).catch(e=>{if(sequence===reviewSequence.current){setError(String(e));setConfirm(false);setReviewPending(false);}});}}/>{zh?'我已核对所选计划和以上影响':'I reviewed the selected plan and consequences'}</label><button disabled={busy||!confirm||reviewPending} onClick={()=>void run(async()=>{const review=lifecycleReview.current;if(!review||review.snapshot!==JSON.stringify(selected))throw Error('STALE_INPUT');await coachPlanService.lifecycle(selected.plan.id,selected.plan.revision,review.generation,action,note,review.context);setConfirm(false);setNotice(zh?'计划状态已更新。':'Plan status updated.');onState?.('success');})}>{zh?'确认更新状态':'Confirm status change'}</button></>}
 </section>;
}
