import { AppIcon, StatusIcon } from './AppIcon';
import {useEffect,useRef,useState} from 'react';
import {createSummaryClient,createSummaryRequest,assertSummaryCurrent,summaryEligible,type SummaryResponse,type SummaryStatus} from '../../ai/summary-client';
import {stageSummaryService,type StageSummaryResult} from '../../application/stage-summary';
import type {StageSummaryRequest} from '../../backend/contracts';
import {statusFeedback} from '../../ai/status-feedback';
type PreparedStage=Extract<StageSummaryResult,{ok:true}>;
export function StageSummaryAi({prepared,locale}:{prepared:PreparedStage|undefined;locale:'en'|'zh'}){
 const zh=locale==='zh',t=(en:string,cn:string)=>zh?cn:en;
 const client=useRef(createSummaryClient()),serial=useRef(0),actionSequence=useRef(0),abort=useRef<AbortController|undefined>(undefined),lock=useRef(false);
 const [connected,setConnected]=useState(false),[status,setStatus]=useState<SummaryStatus>(),[request,setRequest]=useState<StageSummaryRequest>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(false);
 const [received,setReceived]=useState<{response:SummaryResponse;request:StageSummaryRequest}>();
 useEffect(()=>{++serial.current;++actionSequence.current;abort.current?.abort();setRequest(undefined);setConfirmed(false);setStatus(undefined);setBusy(false);lock.current=false;return()=>{++serial.current;++actionSequence.current;abort.current?.abort();};},[prepared,locale]);
 async function readStatus(){try{const next=await client.current.status();setStatus(next);if(next.pending!==undefined||next.reconciliationRequired!==undefined)setPending((next.pending??0)>0||next.reconciliationRequired===true);}catch{setStatus(undefined);throw new Error('CONTROL_UNAVAILABLE');}}
 const eligible=summaryEligible(status)&&!pending;
 async function run(action:()=>Promise<void>){if(lock.current)return;const actionId=++actionSequence.current;lock.current=true;setBusy(true);setError('');try{await action();}catch(reason){if(actionId!==actionSequence.current)return;const code=reason instanceof Error?reason.message:'CONTROL_UNAVAILABLE';if(code==='STALE_STAGE'||code==='STALE_RESTORE_GENERATION'){setConfirmed(false);setRequest(undefined);}setError(code==='STALE_STAGE'||code==='STALE_RESTORE_GENERATION'||code==='CANCELLED_MAY_BE_CHARGED'?code:/^[A-Z_]+$/.test(code)?code:'CONTROL_UNAVAILABLE');if(code==='ACCOUNTING_PENDING')setPending(true);}finally{if(actionId===actionSequence.current){lock.current=false;setBusy(false);}}}
 async function send(){
  if(!request||!confirmed||!eligible)throw new Error('CONFIRMATION_REQUIRED');const input=request,sequence=++serial.current;
  const fresh=await stageSummaryService.prepare(input.stage.selection,Date.now());assertSummaryCurrent(input,fresh);if(sequence!==serial.current)return;
  const controller=new AbortController();abort.current=controller;setConfirmed(false);
  let response:SummaryResponse;try{response=await client.current.submit(input,controller.signal);}catch(reason){if(sequence!==serial.current)return;throw reason;}finally{if(abort.current===controller)abort.current=undefined;}if(sequence!==serial.current)return;
  if(response.accounting==='pending')setPending(true);
  const after=await stageSummaryService.prepare(input.stage.selection,Date.now());assertSummaryCurrent(input,after);if(sequence!==serial.current)return;
  setReceived({response,request:input});await readStatus();
 }
 async function cancel(){const id=request?.requestId;++serial.current;++actionSequence.current;abort.current?.abort();abort.current=undefined;setConfirmed(false);setError('CANCELLED_MAY_BE_CHARGED');setPending(true);setBusy(false);lock.current=false;if(id)try{await client.current.cancel(id);}catch{setStatus(undefined);}}
 const feedback=error==='STALE_STAGE'?t('Selected facts changed. Prepare and confirm a new sending preview.','所选事实已变化，请重新准备并确认发送预览。'):error==='STALE_RESTORE_GENERATION'?t('The local library was restored. This sending confirmation is invalid.','本地库已恢复，本次发送确认已失效。'):error==='CANCELLED_MAY_BE_CHARGED'?t('Cancelled locally. A submitted request may still incur a fee; no refund is promised.','已在本地取消。已提交请求仍可能产生费用，不保证退款。'):error?statusFeedback(error,locale):'';
 return <section aria-label={t('AI stage summary','AI 阶段总结')} style={{overflowWrap:'anywhere',minWidth:0}}>
  <h3>{t('AI stage summary','AI 阶段总结')}</h3><p>{t('Optional backend summary. Preparing local facts does not send them. No new plan or training record is created.','可选后端总结。本地准备不发送事实，不创建新计划或训练记录。')}</p>
  <button disabled={busy||!prepared} onClick={()=>void run(async()=>{setConnected(true);await readStatus();})}>{t(connected?'Refresh summary qualification':'Connect summary backend',connected?'刷新总结资格':'连接总结后端')}</button>
  {!status?<p>{t('Summary qualification and allowance: unknown.','总结资格和额度：未知。')}</p>:<p>{t('Summary allowance occupied','总结次数占用')}: {status.used.summary??t('unknown','未知')}/{status.limits.summary??t('unknown','未知')} · {status.summaryAvailable===true?t('Summary enabled','总结已启用'):status.summaryAvailable===false?t('Summary not enabled','总结未启用'):t('Summary availability: unknown','总结是否启用：未知')}</p>}
  {pending&&<p role="status"><AppIcon name="info"/>{t('Accounting is pending. The full reservation remains occupied; new requests are blocked until reconciliation. Returned summaries remain available.','费用待核算，完整预留仍被占用；核算完成前不能新请求。已返回总结仍可查看。')}</p>}
  <button disabled={busy||!prepared||!eligible} onClick={()=>void run(async()=>{if(!prepared)return;const sequence=serial.current,next=await createSummaryRequest(prepared,locale);if(sequence!==serial.current)return;setRequest(next);setConfirmed(false);})}>{t('Preview summary sending','预览总结发送')}</button>
  {request&&<section aria-label={t('Summary sending scope','总结发送范围')}><p>{request.stage.range.from} → {request.stage.range.to} · {request.stage.range.timeZone}</p><p>{t('Selected fields and counts are shown below; notes and goal snapshots are included. No complete backup, credential, report or manifest is sent.','以下展示所选字段和数量，包含备注及目标快照；不发送完整备份、凭据、统计报告或清单。')}</p><p>{request.stage.payload.sessions.length} {t('sessions','训练')} · {request.stage.payload.sets.length} {t('sets','组')} · {request.stage.payload.scheduledWorkouts.length} {t('tasks','任务')} · {request.stage.payload.bodyWeights.length} {t('weight observations','体重观测')} · {request.stage.goals.length} {t('goal snapshots','目标快照')} · {request.stage.completionLinks.length} {t('outside-range completion identity links (no sets or notes)','范围外完成身份关联（不含组或备注）')}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(request,null,2)}</pre><label><input type="checkbox" disabled={busy||!eligible} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t('I confirm this summary sending scope','我确认本次总结发送范围')}</label><button disabled={busy||!confirmed||!eligible} onClick={()=>void run(send)}>{t('Send confirmed summary','发送已确认总结')}</button></section>}
  {busy&&<p aria-live="polite">{t('Processing summary…','正在处理总结…')}</p>}{busy&&abort.current&&<button onClick={()=>void cancel()}>{t('Cancel summary request','取消总结请求')}</button>}
  {received&&<section aria-label={t('Returned stage summary','已返回阶段总结')}><p>{t('Source: backend result','来源：后端结果')} · {received.request.stage.range.from} → {received.request.stage.range.to} · {received.request.stage.range.timeZone}</p><p>{t('Accounting at receipt','收到时核算状态')}: {received.response.accounting==='pending'?t('pending','待核算'):t('settled','已核算')}</p><p style={{whiteSpace:'pre-wrap'}}>{received.response.result.summary}</p><h4>{t('Next-stage advice (text only)','下一阶段建议（仅文本）')}</h4><ul>{received.response.result.nextStageAdvice.map((item,index)=><li key={index}>{item}</li>)}</ul><p>{t('This advice does not create or update a plan.','该建议不会创建或更新计划。')}</p></section>}
  {feedback&&<p role="alert"><StatusIcon status="warning"/>{feedback} {error}</p>}
 </section>;
}
