import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Link} from 'react-router-dom';
import {AiWorkflow,type AiClient} from '../../ai/workflow';
import {createDemoAiClient,createFetchAiClient,disabledAiClient} from '../../ai/client';
import {statusFeedback} from '../../ai/status-feedback';
import {createAiContextService,type AiContextCapture} from '../../application/ai-context';
import {assertPreviewCurrent} from '../../ai/preview-guard';
import {createAiCandidateService,type AiSaveToken} from '../../application/ai-candidate-save';
import {repository} from '../../persistence/repository';
import type {AiRequest} from '../../backend/contracts';
import type {PlannedExercise} from '../../domain/models';
import type {HistoryManifest} from '../../application/history-context';
import {AiCandidateEditor} from '../components/AiCandidateEditor';
const contextService=createAiContextService(repository);
const candidateService=createAiCandidateService(repository);
type Fields={experience:string;equipment:string;minutes:string;height:string;weight:string;location:string;preference:string;constraints:string};
type ContentReceipt={source:'demo'|'backend';accounting:'settled'|'pending'|undefined};
const blank:Fields={experience:'',equipment:'',minutes:'',height:'',weight:'',location:'',preference:'',constraints:''};
export function AiPage(){
 const {i18n}=useTranslation();const locale=i18n.resolvedLanguage==='zh'?'zh':'en',zh=locale==='zh';const t=(en:string,cn:string)=>zh?cn:en;
 const flow=useRef(new AiWorkflow(disabledAiClient));const [,redraw]=useState(0);const update=()=>redraw(v=>v+1);
 const [mode,setMode]=useState<'disabled'|'demo'|'backend'>('disabled'),[code,setCode]=useState(''),[status,setStatus]=useState<Awaited<ReturnType<AiClient['status']>>>();
 const [goal,setGoal]=useState(''),[interpretation,setInterpretation]=useState(''),[date,setDate]=useState(''),[zone,setZone]=useState('');
 const [fields,setFields]=useState<Fields>(blank),[history,setHistory]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [manifest,setManifest]=useState<HistoryManifest>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [token,setToken]=useState<AiSaveToken>(),[items,setItems]=useState<PlannedExercise[]>([]),[name,setName]=useState(''),[saved,setSaved]=useState(false);
 const [pendingAccounting,setPendingAccounting]=useState(false);
 const [interpretationReceipt,setInterpretationReceipt]=useState<ContentReceipt>(),[planReceipt,setPlanReceipt]=useState<ContentReceipt>();
 const sendingContext=useRef<AiContextCapture|undefined>(undefined);
 const generatedRequest=useRef<Extract<AiRequest,{operation:'generate'}>|undefined>(undefined);const lock=useRef(false);
 useEffect(()=>{let live=true;void contextService.capture().then(capture=>{if(!live)return;setZone(capture.profile.timeZone);const p=capture.profile.trainingPreferences;if(p){setGoal(p.goal??'');flow.current.setGoal(p.goal??'');setFields({experience:p.experience??'',equipment:p.availableEquipment?.join(', ')??'',minutes:p.sessionMinutes?.toString()??'',height:p.heightCm?.toString()??'',weight:p.weightGrams===undefined?'':String(p.weightGrams/1000),location:p.trainingLocation??'',preference:p.exercisePreferences?.length===0?'none':p.exercisePreferences?.[0]??'',constraints:p.constraints??''});}}).catch(()=>{if(live)setError('LOCAL_DATA_UNAVAILABLE');});return()=>{live=false;flow.current.dispose();};},[]);
 useEffect(()=>{flow.current.invalidateInputs();setConfirmed(false);},[locale]);
 function change(){flow.current.invalidateInputs();setConfirmed(false);setToken(undefined);setMessage('');setError('');}
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(reason){const code=reason instanceof Error?('code' in reason?String(reason.code):reason.message):'CONTROL_UNAVAILABLE';setError(code);if(code==='ACCOUNTING_PENDING')setPendingAccounting(true);if(['QUALIFICATION_REQUIRED','SUBJECT_EXPIRED','SUBJECT_NOT_FOUND','CONTROL_UNAVAILABLE'].includes(code))setStatus(undefined);}finally{lock.current=false;setBusy(false);update();}}
 async function readStatus(targetMode=mode){try{const next=await flow.current.client.status();setStatus(next);if(targetMode==='backend'&&(next.pending!==undefined||next.reconciliationRequired!==undefined))setPendingAccounting((next.pending??0)>0||next.reconciliationRequired===true);}catch(reason){setStatus(undefined);throw reason;}}
 function switchClient(client:AiClient,nextMode:'demo'|'backend'){
  flow.current.dispose();flow.current=new AiWorkflow(client);flow.current.setGoal(goal);
  setMode(nextMode);setStatus(undefined);setConfirmed(false);setManifest(undefined);
 }
 function setField(key:keyof Fields,value:string){change();setFields(old=>({...old,[key]:value}));}
 const preview=flow.current.preview;const requestsBlocked=mode==='backend'&&(pendingAccounting||(status?.pending??0)>0||status?.reconciliationRequired===true);
 function receiptText(receipt:ContentReceipt){return (receipt.source==='demo'?t('Source: local demo fixture.','来源：本地演示样例。'):t('Source: backend candidate.','来源：后端候选。'))+(receipt.accounting==='pending'?t(' Accounting at receipt: pending; this does not report the current settled fee.',' 收到时核算状态：待核算；这不表示当前实际结算费用。'):receipt.accounting==='settled'?t(' Accounting at receipt: settled.',' 收到时核算状态：已核算。'):'');}
 const errorText=error?statusFeedback(error,locale)+' '+(/^[A-Z_]+$/.test(error)?error:'')+(error.includes('PENDING')||error.includes('CANCELLED')?t(' A submitted request may have incurred a cost; cancellation does not promise a refund.',' 已提交请求可能产生费用，取消不保证退款。'):''):'';
 return <section aria-label={t('AI plan assistant','AI 计划助手')}><h1>{t('AI plan assistant','AI 计划助手')}</h1><p>{t('Adult general fitness only. Manual training does not require AI.','仅用于成年人一般健身，手动训练不需要 AI。')}</p><Link to="/plans">{t('Back to plans','返回计划')}</Link>
 {mode==='disabled'&&<p>{t('AI is disabled. Local training remains available.','AI 尚未启用，本地训练仍可使用。')}</p>}
 {mode!=='demo'&&<button disabled={busy} onClick={()=>void run(async()=>{switchClient(await createDemoAiClient(),'demo');})}>{t('Enter local demo','进入本地演示')}</button>}
 {mode!=='backend'&&<button disabled={busy} onClick={()=>void run(async()=>{switchClient(createFetchAiClient(),'backend');await readStatus('backend');})}>{t('Connect to backend','连接后端')}</button>}
 {mode==='demo'&&<p>{t('Local demo only: no real model or external sending. Use FITNESS-DEMO. Subsequent demo outputs are fixtures, not fitness recommendations; previously received content keeps its own source.','仅本地演示：无真实模型或外部发送。使用 FITNESS-DEMO。后续演示输出是样例，不是健身建议；已收到内容保留各自来源。')}</p>}
 {mode==='backend'&&<p>{t('Same-origin control connection. Connecting only checks qualification; goal and history are sent only after your separate confirmation. Backend availability does not mean models are enabled.','同源控制连接。连接仅查询资格；目标和历史仅在另行确认后发送。后端可用不代表模型已启用。')}</p>}
 <form onSubmit={event=>{event.preventDefault();void run(async()=>{setStatus(undefined);await flow.current.client.redeem(code);await readStatus();});}}><fieldset disabled={mode==='disabled'||busy}><legend>{t('Trial qualification','试用资格')}</legend><label>{t('Invitation code','邀请码')}<input required value={code} onChange={e=>setCode(e.target.value)} autoComplete="off"/></label><button type="submit">{t('Redeem code','兑换邀请码')}</button><button type="button" onClick={()=>void run(readStatus)}>{t('Refresh qualification','刷新资格')}</button></fieldset></form>
 {status?<><p>{t('Trial expiry','试用到期')}: {new Date(status.expiresAt).toISOString()} · {status.period} · {t('Understanding / plan allowance occupied','理解／计划次数占用')}: {status.used.understand}/{status.limits.understand} · {status.used.generate}/{status.limits.generate}</p><p>{t('In-flight / awaiting accounting','在途／待核算')}: {status.pending??t('unknown','未知')} · {t('Occupied allowance includes in-flight requests; available personal allowance does not guarantee project budget admission.','次数占用包含在途请求；个人有余次不代表项目预算一定允许调用。')}</p></>:<p>{t('Qualification and remaining quota: unknown.','资格和剩余额度：未知。')}</p>}
 {status&&!status.aiEnabled&&<p>{statusFeedback('AI_DISABLED',locale)}</p>}
 <fieldset disabled={busy}><legend>{t('Goal understanding','目标理解')}</legend><label>{t('Goal text','目标文本')}<textarea disabled={!status?.aiEnabled} aria-label={t('Goal text','目标文本')} value={goal} onChange={e=>{change();setInterpretation('');setInterpretationReceipt(undefined);setGoal(e.target.value);flow.current.setGoal(e.target.value);}}/></label><button disabled={!goal.trim()||!status?.aiEnabled||requestsBlocked} onClick={()=>void run(async()=>{const capture=await contextService.capture();await flow.current.previewUnderstanding(locale,capture.restoreGeneration);sendingContext.current=capture;setManifest(undefined);setConfirmed(false);})}>{t('Preview goal sending','预览目标发送')}</button>
 <label>{t('Goal interpretation','目标理解')}<textarea disabled={!status?.aiEnabled&&!interpretationReceipt} aria-label={t('Goal interpretation','目标理解')} value={interpretation} onChange={e=>{setInterpretation(e.target.value);flow.current.confirmedGoal='';change();}}/></label>{interpretationReceipt&&<p aria-label={t('Interpretation source','理解来源')}>{receiptText(interpretationReceipt)}</p>}<button disabled={!interpretation.trim()||(!status?.aiEnabled&&!interpretationReceipt)} onClick={()=>{flow.current.confirmGoal(interpretation);change();update();}}>{t('Confirm goal interpretation','确认目标理解')}</button>{flow.current.confirmedGoal&&<p>{t('Goal interpretation is confirmed.','目标理解已确认。')}</p>}</fieldset>
 <form onSubmit={event=>{event.preventDefault();void run(async()=>{const capture=await contextService.capture(history?{from,to,sources:['sessions','scheduledWorkouts','bodyWeights'],maxUtf8Bytes:32000}:undefined);setZone(capture.profile.timeZone);
  await flow.current.previewGeneration({locale,restoreGeneration:capture.restoreGeneration,dates:[date],timeZone:capture.profile.timeZone,catalogVersion:1,conditions:{experience:fields.experience,availableEquipment:fields.equipment.split(',').map(s=>s.trim()).filter(Boolean),sessionMinutes:Number(fields.minutes),heightCm:Number(fields.height),weightGrams:Math.round(Number(fields.weight)*1000),trainingLocation:fields.location as 'home'|'gym'|'outdoors'|'other',exercisePreferences:fields.preference==='none'?[]:[fields.preference as 'strength'|'cardio'|'bodyweight'],constraints:fields.constraints},...(capture.history?{history:capture.history}:{})});sendingContext.current=capture;setManifest(capture.manifest);setConfirmed(false);});}}><fieldset disabled={busy||!flow.current.confirmedGoal}><legend>{t('One specific date and conditions','一个具体日期与训练条件')}</legend><p>{t('Calendar time zone','日历时区')}: {zone} · {t('One date per request and save in this phase.','本期一次请求及保存一天。')}</p><label>{t('Specific date','具体日期')}<input required type="date" value={date} onChange={e=>{change();setDate(e.target.value);}}/></label>
 <label>{t('Experience','训练经验')}<select aria-label={t('Experience','训练经验')} required value={fields.experience} onChange={e=>setField('experience',e.target.value)}><option value="">—</option>{['beginner','intermediate','experienced'].map(v=><option key={v} value={v}>{t(v,({beginner:'初学者',intermediate:'有一定经验',experienced:'经验丰富',home:'居家',gym:'健身房',outdoors:'户外',other:'其他',none:'无特定偏好',strength:'力量',cardio:'有氧',bodyweight:'自重'} as Record<string,string>)[v])}</option>)}</select></label>
 <label>{t('Available equipment','可用器械')}<input required value={fields.equipment} placeholder={t('Enter none explicitly for no equipment','无器械请明确填写 none')} onChange={e=>setField('equipment',e.target.value)}/></label>
 {(['minutes','height','weight'] as const).map(key=><label key={key}>{key==='minutes'?t('Session minutes','每次分钟数'):key==='height'?t('Height (cm)','身高（厘米）'):t('Weight (kg)','体重（千克）')}<input required type="number" min={1} step={key==='weight'?'0.001':'1'} value={fields[key]} onChange={e=>setField(key,e.target.value)}/></label>)}
 <label>{t('Location','场地')}<select aria-label={t('Location','场地')} required value={fields.location} onChange={e=>setField('location',e.target.value)}><option value="">—</option>{['home','gym','outdoors','other'].map(v=><option key={v} value={v}>{t(v,({beginner:'初学者',intermediate:'有一定经验',experienced:'经验丰富',home:'居家',gym:'健身房',outdoors:'户外',other:'其他',none:'无特定偏好',strength:'力量',cardio:'有氧',bodyweight:'自重'} as Record<string,string>)[v])}</option>)}</select></label><label>{t('Preference','运动偏好')}<select aria-label={t('Preference','运动偏好')} required value={fields.preference} onChange={e=>setField('preference',e.target.value)}><option value="">—</option>{['none','strength','cardio','bodyweight'].map(v=><option key={v} value={v}>{t(v,({beginner:'初学者',intermediate:'有一定经验',experienced:'经验丰富',home:'居家',gym:'健身房',outdoors:'户外',other:'其他',none:'无特定偏好',strength:'力量',cardio:'有氧',bodyweight:'自重'} as Record<string,string>)[v])}</option>)}</select></label><label>{t('Constraints','限制条件')}<textarea aria-label={t('Constraints','限制条件')} value={fields.constraints} onChange={e=>setField('constraints',e.target.value)}/></label>
 <label><input type="checkbox" checked={history} onChange={e=>{change();setHistory(e.target.checked);}}/>{t('Include selected training history','包含选定训练历史')}</label>{history&&<><label>{t('History from','历史开始日期')}<input required type="date" value={from} onChange={e=>{change();setFrom(e.target.value);}}/></label><label>{t('History to','历史结束日期')}<input required type="date" value={to} onChange={e=>{change();setTo(e.target.value);}}/></label></>}
 <button type="submit" disabled={requestsBlocked||!status?.aiEnabled}>{t('Preview plan sending','预览计划发送')}</button></fieldset></form>
 {preview&&<section aria-label={t('This sending scope','本次发送范围')}><h2>{t('Review this exact request','核对本次完整请求')}</h2>{preview.operation==='generate'&&!preview.history&&<p>{t('This request does not use training history.','本次请求未参考训练历史。')}</p>}<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(preview,null,2)}</pre>{manifest&&<details open><summary>{t('History fields, sources, counts and version','历史字段、来源、数量与版本')}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(manifest,null,2)}</pre></details>}
 <label><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('I confirm this sending scope','我确认本次发送范围')}</label><button disabled={busy||!confirmed||requestsBlocked} onClick={()=>void run(async()=>{const current=flow.current.preview;if(!current)throw new Error('CONFIRMATION_REQUIRED');const capture=await contextService.capture(current.operation==='generate'&&current.history?{from:current.history.range.from,to:current.history.range.to,sources:JSON.parse(current.history.text).sources,maxUtf8Bytes:32000}:undefined);if(!sendingContext.current)throw new Error('STALE_SENDING_SCOPE');assertPreviewCurrent(current,sendingContext.current,capture);flow.current.confirmSending(current.sendConfirmation);const sending=flow.current.send();update();await sending;setConfirmed(false);if(flow.current.accounting==='pending')setPendingAccounting(true);if(flow.current.error.startsWith('CANCELLED'))return;
  const receipt:ContentReceipt={source:mode==='demo'?'demo':'backend',accounting:flow.current.accounting};if(current.operation==='understand'){setInterpretation((flow.current.candidate as {interpretedGoal:string}).interpretedGoal);setInterpretationReceipt(receipt);}else{generatedRequest.current=current;const candidate=flow.current.candidate as {days:{date:string;exercises:PlannedExercise[]}[]};setItems(structuredClone(candidate.days[0].exercises));setPlanReceipt(receipt);setName(t('AI date plan','AI 日期计划'));setSaved(false);setToken(undefined);setToken(await candidateService.prepare(current,candidate));}await readStatus();})}>{t('Send confirmed request','发送已确认请求')}</button></section>}
 {busy&&<p aria-live="polite">{t('Processing…','处理中…')}</p>}{flow.current.busy&&<button onClick={()=>{void flow.current.cancel().then(()=>{setError(flow.current.error);update();});}}>{t('Cancel request','取消请求')}</button>}
 {mode==='backend'&&pendingAccounting&&<p role="status">{statusFeedback(planReceipt?.source==='backend'||interpretationReceipt?.source==='backend'?'CANDIDATE_ACCOUNTING_PENDING':'ACCOUNTING_PENDING',locale)}</p>}
 {items.length>0&&planReceipt&&<p aria-label={t('Candidate source','候选来源')}>{receiptText(planReceipt)}</p>}
 {items.length>0&&<><p>{t('Candidate date','候选日期')}: {generatedRequest.current?.dates[0]}</p><AiCandidateEditor name={name} items={items} locale={locale} disabled={busy||saved} canSave={Boolean(token)} onName={setName} onItems={setItems} onSave={()=>void run(async()=>{if(!token||!generatedRequest.current)throw new Error('STALE_CANDIDATE');await candidateService.save(token,[{date:generatedRequest.current.dates[0],name,exercises:items.map((item,order)=>({...item,order}))}]);setSaved(true);setMessage(t('Candidate saved locally. No training was completed.','候选已保存到本地，未完成任何训练。'));})}/></>}
 {errorText&&<p role="alert">{errorText}</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
