import { StrictMode, Suspense, lazy } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import './i18n';
import './ui/theme.css';
import './ui/shared.css';
import { startFeatureFlags } from './application/feature-flags';
import { startFeatureRuntime } from './application/feature-runtime';
startFeatureRuntime();
startFeatureFlags();
import { startMonitoring } from './application/monitoring-client';
startMonitoring();
const MainlineApp = lazy(() => import('./ui/mainline/MainlineApp'));
const ManagementPage = lazy(() => import('./ui/pages/ManagementPage').then(module => ({ default: module.ManagementPage })));
const admin = location.pathname === '/admin' || location.pathname.startsWith('/admin/');
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><Suspense fallback={null}>{admin ? <ManagementPage /> : <MainlineApp />}</Suspense></BrowserRouter></StrictMode>);
