import {describe,it,expect} from 'vitest';
import {AiWorkflow,type AiClient} from '../../src/ai/workflow';
function harness(){let calls=0;const client:AiClient={status:async()=>({expiresAt:Date.now()+1000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},aiEnabled:true}),redeem:async()=>{},submit:async request=>{calls++;return {requestId:request.requestId,result:request.operation==='understand'?{interpretedGoal:'Confirmed interpretation'}:{days:[]}};},cancel:async()=>{}};return {flow:new AiWorkflow(client),calls:()=>calls};}
describe('AI page confirmation and response lifecycle',()=>{
 it('late cancellation failure cannot overwrite a newer successful request',async()=>{const {flow}=harness();flow.setGoal('Goal');let preview=await flow.previewUnderstanding('en',0);flow.confirmSending(preview.sendConfirmation);let finish!:(value:any)=>void;let rejectCancel!:(reason:Error)=>void;flow.client.submit=()=>new Promise(resolve=>{finish=resolve;});flow.client.cancel=()=>new Promise((_,reject)=>{rejectCancel=reject;});const first=flow.send();const cancelling=flow.cancel();finish({requestId:preview.requestId,result:{interpretedGoal:'Old'}});await first;flow.client.submit=async request=>({requestId:request.requestId,result:{interpretedGoal:'New'}});preview=await flow.previewUnderstanding('en',0);flow.confirmSending(preview.sendConfirmation);await flow.send();rejectCancel(new Error('offline'));await cancelling;expect(flow.error).toBe('');expect(flow.candidate).toEqual({interpretedGoal:'New'});});
 it('a goal changed while a preview hash is being prepared cannot publish an old preview',async()=>{const {flow}=harness();flow.setGoal('Original');const prepared=flow.previewUnderstanding('en',0);flow.setGoal('Changed');await expect(prepared).rejects.toThrow('STALE_PREVIEW');expect(flow.preview).toBeUndefined();});
 it('requires this preview confirmation before any call',async()=>{const {flow,calls}=harness();flow.setGoal('Goal');await flow.previewUnderstanding('en',0);await expect(flow.send()).rejects.toThrow('CONFIRMATION_REQUIRED');expect(calls()).toBe(0);});
 it('goal change invalidates both confirmations and stale preview',async()=>{const {flow,calls}=harness();flow.setGoal('Goal');flow.confirmGoal('Understanding');const preview=await flow.previewUnderstanding('en',0);flow.confirmSending(preview.sendConfirmation);flow.setGoal('New goal');expect(flow.confirmedGoal).toBe('');expect(flow.preview).toBeUndefined();await expect(flow.send()).rejects.toThrow();expect(calls()).toBe(0);});
 it('understanding request never includes conditions or history',async()=>{const {flow}=harness();flow.setGoal('Goal');const request=await flow.previewUnderstanding('zh',2);expect(Object.keys(request).sort()).toEqual(['contractVersion','goalText','locale','operation','requestId','restoreGeneration','sendConfirmation'].sort());flow.confirmSending(request.sendConfirmation);await flow.send();expect(flow.confirmedGoal).toBe('');expect(flow.candidate).toEqual({interpretedGoal:'Confirmed interpretation'});});
 it('generation requires goal confirmation and rejects excess date count',async()=>{const {flow}=harness();flow.setGoal('Goal');const input={locale:'en' as const,restoreGeneration:0,dates:['2026-10-05'],timeZone:'UTC',catalogVersion:1 as const,conditions:{}};await expect(flow.previewGeneration(input)).rejects.toThrow('GOAL_CONFIRMATION_REQUIRED');flow.confirmGoal('Understanding');await expect(flow.previewGeneration({...input,dates:['2026-10-05','2026-10-06']})).rejects.toThrow('DATE_BOUND_EXCEEDED');});
 it('input change and failed new request do not erase an already returned candidate',async()=>{const {flow}=harness();flow.setGoal('Goal');let preview=await flow.previewUnderstanding('en',0);flow.confirmSending(preview.sendConfirmation);await flow.send();flow.invalidateInputs();expect(flow.candidate).toEqual({interpretedGoal:'Confirmed interpretation'});flow.client.submit=async()=>{throw new Error('ACCOUNTING_PENDING');};preview=await flow.previewUnderstanding('en',0);flow.confirmSending(preview.sendConfirmation);await expect(flow.send()).rejects.toThrow('ACCOUNTING_PENDING');expect(flow.candidate).toEqual({interpretedGoal:'Confirmed interpretation'});expect(flow.error).toBe('ACCOUNTING_PENDING');});
 it('cancel ignores a late response and does not claim a refund',async()=>{const {flow}=harness();flow.setGoal('Goal');const preview=await flow.previewUnderstanding('en',0);flow.confirmSending(preview.sendConfirmation);let finish!:(value:any)=>void;flow.client.submit=()=>new Promise(resolve=>{finish=resolve;});const pending=flow.send();await flow.cancel();finish({requestId:preview.requestId,result:{interpretedGoal:'Late'}});await pending;expect(flow.candidate).toBeUndefined();expect(flow.busy).toBe(false);expect(flow.error).toBe('CANCELLED_MAY_BE_CHARGED');});
});
