import {describe,it,expect} from 'vitest';
import {eligibleReminder,quietAt,scheduledInstant,defaultCoachPreferences,type CoachLedger,type ReminderContext,type ReminderSource} from '../../src/domain/coach-reminders';
const now=Date.parse('2026-10-09T04:00:00Z');
const ledger=():CoachLedger=>({id:'coach:a',preferences:{...defaultCoachPreferences('Asia/Shanghai'),enabled:true},records:[],watermark:now-1000,snoozeUntil:0,generation:0,initializedAt:now-3600000});
const context=():ReminderContext=>({now,generation:0,profileId:'a',foreground:true,focused:true,training:false,onboarding:false,chat:false,modal:false,idleSince:now-60001});
const source:ReminderSource={id:'w:a:v:2026-10-09:13:00',kind:'workout',taskId:'a',versionId:'v',date:'2026-10-09',startTime:'13:00',timeZone:'Asia/Shanghai',from:now-30*60000,until:now+30*60000};
describe('reminders civil time and admission',()=>{
 it.each([[-90,true],[-60,true],[-30,true],[1,false],[-91,false],[-29,false]])('T%imin => %s',(delta,ok)=>{const at=now+3600000+delta*60000;const l=ledger();l.watermark=0;expect(Boolean(eligibleReminder([source],l,{...context(),now:at}))).toBe(ok);});
 it.each(['2024-02-29','2026-12-31','2027-01-01'])('valid calendar %s',date=>expect(scheduledInstant(date,'12:00','Asia/Shanghai')).toBe(Date.parse(date+'T04:00:00Z')));
 it('DST gaps rejected and repeats select earliest',()=>{expect(scheduledInstant('2026-03-08','02:30','America/New_York')).toBeNull();expect(scheduledInstant('2026-11-01','01:30','America/New_York')).toBe(Date.parse('2026-11-01T05:30:00Z'));expect(scheduledInstant('2026-10-09','','Asia/Shanghai')).toBeNull();expect(scheduledInstant('2026-10-09','12:00','invalid')).toBeNull();});
 it.each([['21:59',false],['22:00',true],['07:59',true],['08:00',false]])('quiet %s',(time,expected)=>{expect(quietAt(scheduledInstant('2026-10-09',time,'Asia/Shanghai')!,ledger().preferences)).toBe(expected);});
 it.each(['training','onboarding','chat','modal'])('suppresses %s',key=>expect(eligibleReminder([source],ledger(),{...context(),[key]:true})).toBeUndefined());
 it.each(['foreground','focused'])('requires %s',key=>expect(eligibleReminder([source],ledger(),{...context(),[key]:false})).toBeUndefined());
 it('respects disabled, snooze, restore and clock rollback',()=>{const l=ledger();l.preferences.enabled=false;expect(eligibleReminder([source],l,context())).toBeUndefined();l.preferences.enabled=true;l.snoozeUntil=now+1;expect(eligibleReminder([source],l,context())).toBeUndefined();l.snoozeUntil=0;l.watermark=now+1;expect(eligibleReminder([source],l,context())).toBeUndefined();l.watermark=0;expect(eligibleReminder([source],l,{...context(),generation:1})).toBeUndefined();});
 it('daily cap, six-hour cooldown, same task edited, priority',()=>{const l=ledger();const encourage={...source,id:'e',kind:'encourage' as const,taskId:undefined};expect(eligibleReminder([encourage,source],l,context())?.id).toBe(source.id);l.records.push({...source,profileId:'a',generation:0,shownAt:now-7*3600000,day:'2026-10-09',status:'dismissed'});expect(eligibleReminder([{...source,id:'edited',versionId:'v2'}],l,context())).toBeUndefined();expect(eligibleReminder([encourage],l,context())?.id).toBe('e');l.preferences.dailyLimit=1;expect(eligibleReminder([encourage],l,context())).toBeUndefined();l.preferences.dailyLimit=2;l.records[0].shownAt=now-3600000;expect(eligibleReminder([{...source,id:'other',taskId:'b'}],l,context())).toBeUndefined();});
 it('neutral encouragement requires idle and never claims completion',()=>{expect(eligibleReminder([{...source,kind:'encourage'}],ledger(),{...context(),idleSince:now})).toBeUndefined();});
});
