import {describe,it,expect,vi} from 'vitest';
import {createSummaryClient,createSummaryRequest,assertSummaryCurrent,summaryEligible} from '../../src/ai/summary-client';
import {buildStageSummary} from '../../src/application/stage-summary';
import type {HistorySnapshot} from '../../src/application/history-context';
const stamp='2026-10-06T12:00:00.000Z';
function prepared(){const snapshot:HistorySnapshot={capturedAt:stamp,dataRevision:1,restoreGeneration:0,plans:[],planVersions:[],sessions:[],sets:[],scheduledWorkouts:[],bodyWeights:[{id:crypto.randomUUID(),createdAt:stamp,updatedAt:stamp,revision:0,localDate:'2026-10-06',timeZone:'UTC',weightGrams:70000}]};const result=buildStageSummary(snapshot,{kind:'dateRange',from:'2026-10-06',to:'2026-10-06',timeZone:'UTC'});if(!result.ok)throw new Error(result.code);return result;}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status});
describe('summary sending boundaries',()=>{
 it('request includes only the explicit summary stage without report or manifest',async()=>{const result=prepared(),request=await createSummaryRequest(result,'en');expect(Object.keys(request).sort()).toEqual(['contractVersion','locale','operation','requestId','restoreGeneration','sendConfirmation','stage']);expect(request.stage).toHaveProperty('completionLinks');expect(request.stage).not.toHaveProperty('report');expect(request.stage).not.toHaveProperty('manifest');});
 it('ignores unrelated revisions and capture clocks but rejects changed facts and restores',async()=>{const result=prepared(),request=await createSummaryRequest(result,'en'),fresh=structuredClone(result);fresh.manifest.dataRevision++;fresh.manifest.capturedAt='2026-10-06T12:00:01.000Z';fresh.payload.dataRevision++;fresh.payload.capturedAt=fresh.manifest.capturedAt;expect(()=>assertSummaryCurrent(request,fresh)).not.toThrow();fresh.payload.bodyWeights[0].weightGrams++;expect(()=>assertSummaryCurrent(request,fresh)).toThrow('STALE_STAGE');fresh.manifest.restoreGeneration++;expect(()=>assertSummaryCurrent(request,fresh)).toThrow('STALE_RESTORE_GENERATION');});
 it('missing summary capability never fabricates availability or quota',()=>{const status={expiresAt:Date.now()+1000,period:'2026-10',used:{understand:0,generate:0},limits:{understand:8,generate:4},aiEnabled:true};expect(summaryEligible(status)).toBe(false);expect(summaryEligible({...status,summaryAvailable:true,used:{...status.used,summary:0},limits:{...status.limits,summary:4},pending:0,reconciliationRequired:false})).toBe(true);expect(summaryEligible({...status,summaryAvailable:true,used:{...status.used,summary:0},limits:{...status.limits,summary:4},reconciliationRequired:true})).toBe(false);});
 it('valid pending summary preserves accounting metadata with no retry and safe transport',async()=>{const request=await createSummaryRequest(prepared(),'zh'),response={requestId:request.requestId,result:{summary:'合成总结',nextStageAdvice:['逐步增加训练']},context:{restoreGeneration:0,inputDigest:request.sendConfirmation},accounting:'pending'};const fetcher=vi.fn(async(url:unknown,options?:RequestInit)=>{expect(url).toBe('/api/v1/stages/summarize');expect(options).toMatchObject({credentials:'same-origin',cache:'no-store',redirect:'manual'});return json(response);});await expect(createSummaryClient(fetcher).submit(request)).resolves.toEqual(response);expect(fetcher).toHaveBeenCalledTimes(1);});
 it('rejects wrong identity, stale context, invalid text and missing accounting',async()=>{const request=await createSummaryRequest(prepared(),'en'),response={requestId:request.requestId,result:{summary:'Summary',nextStageAdvice:['Advice']},context:{restoreGeneration:0,inputDigest:request.sendConfirmation},accounting:'settled'};for(const delta of [{requestId:crypto.randomUUID()},{context:{restoreGeneration:1,inputDigest:request.sendConfirmation}},{accounting:undefined},{result:{summary:'Summary',nextStageAdvice:[{unsafe:'raw'}]}}])await expect(createSummaryClient(async()=>json({...response,...delta})).submit(request)).rejects.toThrow('CONTROL_UNAVAILABLE');});
 it('redirects, unreadable responses and unknown errors remain sanitized',async()=>{const request=await createSummaryRequest(prepared(),'en');for(const fetcher of [async()=>new Response(null,{status:302}),async()=>new Response('private'),async()=>json({error:'private key'},500),async()=>{throw new Error('private');}])await expect(createSummaryClient(fetcher).submit(request)).rejects.toThrow('CONTROL_UNAVAILABLE');await expect(createSummaryClient(async()=>json({error:'ACCOUNTING_PENDING'},503)).submit(request)).rejects.toThrow('ACCOUNTING_PENDING');});
});
